SELECT 'AZT/3TC' AS 'Title 11',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC', 1) AS '< 1 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC', 2) AS '< 1 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC', 3) AS '< 1 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC') AS '< 1 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC') AS '< 1 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC', 1) AS '1 - 4 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC', 2) AS '1 - 4 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC', 3) AS '1 - 4 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC') AS '1 - 4 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC') AS '1 - 4 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC', 1) AS '5 - 9 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC', 2) AS '5 - 9 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC', 3) AS '5 - 9 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC') AS '5 - 9 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC') AS '5 - 9 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC', 1) AS '10 - 14 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC', 2) AS '10 - 14 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC', 3) AS '10 - 14 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC') AS '10 - 14 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC') AS '10 - 14 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC', 1) AS '15 - 19 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC', 2) AS '15 - 19 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC', 3) AS '15 - 19 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC') AS '15 - 19 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC') AS '15 - 19 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC', 1) AS '> 19 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC', 2) AS '> 19 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC', 3) AS '> 19 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC') AS '> 19 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC') AS '> 19 year pa',
    'AZT/3TC+ATV' AS 'Title 12',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV', 1) AS '< 1 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV', 2) AS '< 1 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV', 3) AS '< 1 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV') AS '< 1 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV') AS '< 1 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV', 1) AS '1 - 4 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV', 2) AS '1 - 4 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV', 3) AS '1 - 4 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV') AS '1 - 4 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV') AS '1 - 4 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV', 1) AS '5 - 9 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV', 2) AS '5 - 9 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV', 3) AS '5 - 9 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV') AS '5 - 9 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV') AS '5 - 9 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV', 1) AS '10 - 14 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV', 2) AS '10 - 14 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV', 3) AS '10 - 14 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV') AS '10 - 14 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV') AS '10 - 14 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV', 1) AS '15 - 19 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV', 2) AS '15 - 19 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV', 3) AS '15 - 19 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV') AS '15 - 19 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV') AS '15 - 19 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV', 1) AS '> 19 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV', 2) AS '> 19 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV', 3) AS '> 19 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV') AS '> 19 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV') AS '> 19 year pa 2',
    'AZT/3TC+ATV/r' AS 'Title 13',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV/r', 1) AS '< 1 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV/r', 2) AS '< 1 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV/r', 3) AS '< 1 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV/r') AS '< 1 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+ATV/r') AS '< 1 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV/r', 1) AS '1 - 4 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV/r', 2) AS '1 - 4 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV/r', 3) AS '1 - 4 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV/r') AS '1 - 4 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+ATV/r') AS '1 - 4 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV/r', 1) AS '5 - 9 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV/r', 2) AS '5 - 9 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV/r', 3) AS '5 - 9 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV/r') AS '5 - 9 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+ATV/r') AS '5 - 9 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV/r', 1) AS '10 - 14 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV/r', 2) AS '10 - 14 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV/r', 3) AS '10 - 14 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV/r') AS '10 - 14 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+ATV/r') AS '10 - 14 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV/r', 1) AS '15 - 19 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV/r', 2) AS '15 - 19 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV/r', 3) AS '15 - 19 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV/r') AS '15 - 19 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+ATV/r') AS '15 - 19 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV/r', 1) AS '> 19 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV/r', 2) AS '> 19 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV/r', 3) AS '> 19 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV/r') AS '> 19 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+ATV/r') AS '> 19 year pa 3',
    'AZT/3TC+DTG' AS 'Title 14',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG', 1) AS '< 1 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG', 2) AS '< 1 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG', 3) AS '< 1 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG') AS '< 1 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG') AS '< 1 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG', 1) AS '1 - 4 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG', 2) AS '1 - 4 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG', 3) AS '1 - 4 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG') AS '1 - 4 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG') AS '1 - 4 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG', 1) AS '5 - 9 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG', 2) AS '5 - 9 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG', 3) AS '5 - 9 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG') AS '5 - 9 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG') AS '5 - 9 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG', 1) AS '10 - 14 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG', 2) AS '10 - 14 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG', 3) AS '10 - 14 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG') AS '10 - 14 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG') AS '10 - 14 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG', 1) AS '15 - 19 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG', 2) AS '15 - 19 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG', 3) AS '15 - 19 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG') AS '15 - 19 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG') AS '15 - 19 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG', 1) AS '> 19 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG', 2) AS '> 19 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG', 3) AS '> 19 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG') AS '> 19 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG') AS '> 19 year pa 4',
    'AZT/3TC+DTG+DRV/r' AS 'Title 15',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG+DRV/r', 1) AS '< 1 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG+DRV/r', 2) AS '< 1 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG+DRV/r', 3) AS '< 1 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG+DRV/r') AS '< 1 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'AZT/3TC+DTG+DRV/r') AS '< 1 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG+DRV/r', 1) AS '1 - 4 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG+DRV/r', 2) AS '1 - 4 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG+DRV/r', 3) AS '1 - 4 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG+DRV/r') AS '1 - 4 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'AZT/3TC+DTG+DRV/r') AS '1 - 4 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG+DRV/r', 1) AS '5 - 9 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG+DRV/r', 2) AS '5 - 9 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG+DRV/r', 3) AS '5 - 9 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG+DRV/r') AS '5 - 9 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'AZT/3TC+DTG+DRV/r') AS '5 - 9 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG+DRV/r', 1) AS '10 - 14 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG+DRV/r', 2) AS '10 - 14 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG+DRV/r', 3) AS '10 - 14 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG+DRV/r') AS '10 - 14 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'AZT/3TC+DTG+DRV/r') AS '10 - 14 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG+DRV/r', 1) AS '15 - 19 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG+DRV/r', 2) AS '15 - 19 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG+DRV/r', 3) AS '15 - 19 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG+DRV/r') AS '15 - 19 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'AZT/3TC+DTG+DRV/r') AS '15 - 19 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG+DRV/r', 1) AS '> 19 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG+DRV/r', 2) AS '> 19 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG+DRV/r', 3) AS '> 19 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG+DRV/r') AS '> 19 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'AZT/3TC+DTG+DRV/r') AS '> 19 year pa 5';