SELECT 'DTG' AS 'Title 21',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'DTG', 1) AS '< 1 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'DTG', 2) AS '< 1 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'DTG', 3) AS '< 1 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'DTG') AS '< 1 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'DTG') AS '< 1 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'DTG', 1) AS '1 - 4 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'DTG', 2) AS '1 - 4 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'DTG', 3) AS '1 - 4 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'DTG') AS '1 - 4 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'DTG') AS '1 - 4 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'DTG', 1) AS '5 - 9 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'DTG', 2) AS '5 - 9 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'DTG', 3) AS '5 - 9 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'DTG') AS '5 - 9 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'DTG') AS '5 - 9 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'DTG', 1) AS '10 - 14 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'DTG', 2) AS '10 - 14 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'DTG', 3) AS '10 - 14 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'DTG') AS '10 - 14 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'DTG') AS '10 - 14 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'DTG', 1) AS '15 - 19 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'DTG', 2) AS '15 - 19 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'DTG', 3) AS '15 - 19 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'DTG') AS '15 - 19 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'DTG') AS '15 - 19 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'DTG', 1) AS '> 19 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'DTG', 2) AS '> 19 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'DTG', 3) AS '> 19 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'DTG') AS '> 19 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'DTG') AS '> 19 year pa',
    'EFV' AS 'Title 22',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'EFV', 1) AS '< 1 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'EFV', 2) AS '< 1 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'EFV', 3) AS '< 1 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'EFV') AS '< 1 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'EFV') AS '< 1 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'EFV', 1) AS '1 - 4 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'EFV', 2) AS '1 - 4 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'EFV', 3) AS '1 - 4 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'EFV') AS '1 - 4 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'EFV') AS '1 - 4 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'EFV', 1) AS '5 - 9 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'EFV', 2) AS '5 - 9 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'EFV', 3) AS '5 - 9 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'EFV') AS '5 - 9 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'EFV') AS '5 - 9 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'EFV', 1) AS '10 - 14 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'EFV', 2) AS '10 - 14 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'EFV', 3) AS '10 - 14 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'EFV') AS '10 - 14 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'EFV') AS '10 - 14 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'EFV', 1) AS '15 - 19 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'EFV', 2) AS '15 - 19 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'EFV', 3) AS '15 - 19 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'EFV') AS '15 - 19 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'EFV') AS '15 - 19 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'EFV', 1) AS '> 19 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'EFV', 2) AS '> 19 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'EFV', 3) AS '> 19 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'EFV') AS '> 19 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'EFV') AS '> 19 year pa 2',
    'INH' AS 'Title 23',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'INH', 1) AS '< 1 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'INH', 2) AS '< 1 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'INH', 3) AS '< 1 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'INH') AS '< 1 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'INH') AS '< 1 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'INH', 1) AS '1 - 4 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'INH', 2) AS '1 - 4 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'INH', 3) AS '1 - 4 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'INH') AS '1 - 4 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'INH') AS '1 - 4 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'INH', 1) AS '5 - 9 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'INH', 2) AS '5 - 9 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'INH', 3) AS '5 - 9 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'INH') AS '5 - 9 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'INH') AS '5 - 9 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'INH', 1) AS '10 - 14 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'INH', 2) AS '10 - 14 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'INH', 3) AS '10 - 14 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'INH') AS '10 - 14 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'INH') AS '10 - 14 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'INH', 1) AS '15 - 19 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'INH', 2) AS '15 - 19 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'INH', 3) AS '15 - 19 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'INH') AS '15 - 19 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'INH') AS '15 - 19 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'INH', 1) AS '> 19 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'INH', 2) AS '> 19 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'INH', 3) AS '> 19 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'INH') AS '> 19 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'INH') AS '> 19 year pa 3',
    'LPV/r' AS 'Title 24',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'LPV/r', 1) AS '< 1 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'LPV/r', 2) AS '< 1 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'LPV/r', 3) AS '< 1 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'LPV/r') AS '< 1 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'LPV/r') AS '< 1 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'LPV/r', 1) AS '1 - 4 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'LPV/r', 2) AS '1 - 4 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'LPV/r', 3) AS '1 - 4 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'LPV/r') AS '1 - 4 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'LPV/r') AS '1 - 4 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'LPV/r', 1) AS '5 - 9 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'LPV/r', 2) AS '5 - 9 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'LPV/r', 3) AS '5 - 9 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'LPV/r') AS '5 - 9 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'LPV/r') AS '5 - 9 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'LPV/r', 1) AS '10 - 14 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'LPV/r', 2) AS '10 - 14 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'LPV/r', 3) AS '10 - 14 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'LPV/r') AS '10 - 14 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'LPV/r') AS '10 - 14 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'LPV/r', 1) AS '15 - 19 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'LPV/r', 2) AS '15 - 19 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'LPV/r', 3) AS '15 - 19 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'LPV/r') AS '15 - 19 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'LPV/r') AS '15 - 19 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'LPV/r', 1) AS '> 19 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'LPV/r', 2) AS '> 19 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'LPV/r', 3) AS '> 19 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'LPV/r') AS '> 19 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'LPV/r') AS '> 19 year pa 4',
    'NVP' AS 'Title 25',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'NVP', 1) AS '< 1 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'NVP', 2) AS '< 1 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'NVP', 3) AS '< 1 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'NVP') AS '< 1 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'NVP') AS '< 1 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'NVP', 1) AS '1 - 4 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'NVP', 2) AS '1 - 4 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'NVP', 3) AS '1 - 4 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'NVP') AS '1 - 4 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'NVP') AS '1 - 4 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'NVP', 1) AS '5 - 9 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'NVP', 2) AS '5 - 9 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'NVP', 3) AS '5 - 9 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'NVP') AS '5 - 9 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'NVP') AS '5 - 9 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'NVP', 1) AS '10 - 14 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'NVP', 2) AS '10 - 14 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'NVP', 3) AS '10 - 14 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'NVP') AS '10 - 14 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'NVP') AS '10 - 14 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'NVP', 1) AS '15 - 19 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'NVP', 2) AS '15 - 19 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'NVP', 3) AS '15 - 19 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'NVP') AS '15 - 19 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'NVP') AS '15 - 19 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'NVP', 1) AS '> 19 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'NVP', 2) AS '> 19 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'NVP', 3) AS '> 19 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'NVP') AS '> 19 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'NVP') AS '> 19 year pa 5';