SELECT 'ABC/3TC+EFV' AS 'Title 6',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+EFV', 1) AS '< 1 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+EFV', 2) AS '< 1 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+EFV', 3) AS '< 1 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+EFV') AS '< 1 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+EFV') AS '< 1 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+EFV', 1) AS '1 - 4 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+EFV', 2) AS '1 - 4 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+EFV', 3) AS '1 - 4 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+EFV') AS '1 - 4 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+EFV') AS '1 - 4 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+EFV', 1) AS '5 - 9 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+EFV', 2) AS '5 - 9 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+EFV', 3) AS '5 - 9 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+EFV') AS '5 - 9 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+EFV') AS '5 - 9 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+EFV', 1) AS '10 - 14 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+EFV', 2) AS '10 - 14 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+EFV', 3) AS '10 - 14 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+EFV') AS '10 - 14 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+EFV') AS '10 - 14 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+EFV', 1) AS '15 - 19 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+EFV', 2) AS '15 - 19 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+EFV', 3) AS '15 - 19 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+EFV') AS '15 - 19 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+EFV') AS '15 - 19 year pa',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+EFV', 1) AS '> 19 year 1st',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+EFV', 2) AS '> 19 year 2nd',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+EFV', 3) AS '> 19 year 3rd',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+EFV') AS '> 19 year aes',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+EFV') AS '> 19 year pa',
    'ABC/3TC+LPV/r' AS 'Title 7',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+LPV/r', 1) AS '< 1 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+LPV/r', 2) AS '< 1 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+LPV/r', 3) AS '< 1 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+LPV/r') AS '< 1 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+LPV/r') AS '< 1 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+LPV/r', 1) AS '1 - 4 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+LPV/r', 2) AS '1 - 4 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+LPV/r', 3) AS '1 - 4 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+LPV/r') AS '1 - 4 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+LPV/r') AS '1 - 4 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+LPV/r', 1) AS '5 - 9 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+LPV/r', 2) AS '5 - 9 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+LPV/r', 3) AS '5 - 9 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+LPV/r') AS '5 - 9 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+LPV/r') AS '5 - 9 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+LPV/r', 1) AS '10 - 14 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+LPV/r', 2) AS '10 - 14 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+LPV/r', 3) AS '10 - 14 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+LPV/r') AS '10 - 14 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+LPV/r') AS '10 - 14 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+LPV/r', 1) AS '15 - 19 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+LPV/r', 2) AS '15 - 19 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+LPV/r', 3) AS '15 - 19 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+LPV/r') AS '15 - 19 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+LPV/r') AS '15 - 19 year pa 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+LPV/r', 1) AS '> 19 year 1st 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+LPV/r', 2) AS '> 19 year 2nd 2',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+LPV/r', 3) AS '> 19 year 3rd 2',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+LPV/r') AS '> 19 year aes 2',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+LPV/r') AS '> 19 year pa 2',
    'ABC/3TC+NVP' AS 'Title 8',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+NVP', 1) AS '< 1 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+NVP', 2) AS '< 1 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+NVP', 3) AS '< 1 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+NVP') AS '< 1 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ABC/3TC+NVP') AS '< 1 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+NVP', 1) AS '1 - 4 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+NVP', 2) AS '1 - 4 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+NVP', 3) AS '1 - 4 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+NVP') AS '1 - 4 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ABC/3TC+NVP') AS '1 - 4 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+NVP', 1) AS '5 - 9 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+NVP', 2) AS '5 - 9 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+NVP', 3) AS '5 - 9 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+NVP') AS '5 - 9 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ABC/3TC+NVP') AS '5 - 9 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+NVP', 1) AS '10 - 14 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+NVP', 2) AS '10 - 14 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+NVP', 3) AS '10 - 14 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+NVP') AS '10 - 14 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ABC/3TC+NVP') AS '10 - 14 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+NVP', 1) AS '15 - 19 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+NVP', 2) AS '15 - 19 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+NVP', 3) AS '15 - 19 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+NVP') AS '15 - 19 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ABC/3TC+NVP') AS '15 - 19 year pa 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+NVP', 1) AS '> 19 year 1st 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+NVP', 2) AS '> 19 year 2nd 3',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+NVP', 3) AS '> 19 year 3rd 3',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+NVP') AS '> 19 year aes 3',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ABC/3TC+NVP') AS '> 19 year pa 3',
    'ATV' AS 'Title 9',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV', 1) AS '< 1 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV', 2) AS '< 1 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV', 3) AS '< 1 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV') AS '< 1 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV') AS '< 1 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV', 1) AS '1 - 4 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV', 2) AS '1 - 4 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV', 3) AS '1 - 4 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV') AS '1 - 4 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV') AS '1 - 4 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV', 1) AS '5 - 9 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV', 2) AS '5 - 9 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV', 3) AS '5 - 9 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV') AS '5 - 9 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV') AS '5 - 9 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV', 1) AS '10 - 14 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV', 2) AS '10 - 14 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV', 3) AS '10 - 14 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV') AS '10 - 14 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV') AS '10 - 14 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV', 1) AS '15 - 19 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV', 2) AS '15 - 19 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV', 3) AS '15 - 19 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV') AS '15 - 19 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV') AS '15 - 19 year pa 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV', 1) AS '> 19 year 1st 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV', 2) AS '> 19 year 2nd 4',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV', 3) AS '> 19 year 3rd 4',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV') AS '> 19 year aes 4',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV') AS '> 19 year pa 4',
    'ATV/r' AS 'Title 10',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV/r', 1) AS '< 1 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV/r', 2) AS '< 1 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV/r', 3) AS '< 1 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV/r') AS '< 1 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 0, 1, 0, 'ATV/r') AS '< 1 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV/r', 1) AS '1 - 4 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV/r', 2) AS '1 - 4 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV/r', 3) AS '1 - 4 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV/r') AS '1 - 4 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 1, 4, 1, 'ATV/r') AS '1 - 4 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV/r', 1) AS '5 - 9 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV/r', 2) AS '5 - 9 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV/r', 3) AS '5 - 9 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV/r') AS '5 - 9 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 5, 9, 1, 'ATV/r') AS '5 - 9 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV/r', 1) AS '10 - 14 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV/r', 2) AS '10 - 14 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV/r', 3) AS '10 - 14 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV/r') AS '10 - 14 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 10, 14, 1, 'ATV/r') AS '10 - 14 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV/r', 1) AS '15 - 19 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV/r', 2) AS '15 - 19 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV/r', 3) AS '15 - 19 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV/r') AS '15 - 19 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 15, 19, 1, 'ATV/r') AS '15 - 19 year pa 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV/r', 1) AS '> 19 year 1st 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV/r', 2) AS '> 19 year 2nd 5',
    getNumberOfTherapeuticLineARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV/r', 3) AS '> 19 year 3rd 5',
    getNumberOfAES_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV/r') AS '> 19 year aes 5',
    getNumberOfPA_ARVDispensed('#startDate#','#endDate#', 20, 200, 1, 'ATV/r') AS '> 19 year pa 5';