SELECT 'ABC/3TC' AS 'Title 1',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ABC/3TC') AS 'prescribed 1',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ABC/3TC') AS 'dispensed 1',
    'ABC/3TC+ATV' AS 'Title 2',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ABC/3TC+ATV') AS 'prescribed 2',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ABC/3TC+ATV') AS 'dispensed 2',
    'ABC/3TC+ATV/r' AS 'Title 3',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ABC/3TC+ATV/r') AS 'prescribed 3',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ABC/3TC+ATV/r') AS 'dispensed 3',
    'ABC/3TC+DTG' AS 'Title 4',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ABC/3TC+DTG') AS 'prescribed 4',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ABC/3TC+DTG') AS 'dispensed 4',
    'ABC/3TC+DTG+DRV/r' AS 'Title 5',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ABC/3TC+DTG+DRV/r') AS 'prescribed 5',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ABC/3TC+DTG+DRV/r') AS 'dispensed 5',
    'ABC/3TC+EFV' AS 'Title 6',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ABC/3TC+EFV') AS 'prescribed 6',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ABC/3TC+EFV') AS 'dispensed 6',
    'ABC/3TC+LPV/r' AS 'Title 7',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ABC/3TC+LPV/r') AS 'prescribed 7',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ABC/3TC+LPV/r') AS 'dispensed 7',
    'ABC/3TC+NVP' AS 'Title 8',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ABC/3TC+NVP') AS 'prescribed 8',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ABC/3TC+NVP') AS 'dispensed 8',
    'ATV' AS 'Title 9',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ATV') AS 'prescribed 9',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ATV') AS 'dispensed 9',
    'ATV/r' AS 'Title 10',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'ATV/r') AS 'prescribed 10',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'ATV/r') AS 'dispensed 10',
    'AZT/3TC' AS 'Title 11',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'AZT/3TC') AS 'prescribed 11',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'AZT/3TC') AS 'dispensed 11',
    'AZT/3TC+ATV' AS 'Title 12',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'AZT/3TC+ATV') AS 'prescribed 12',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'AZT/3TC+ATV') AS 'dispensed 12',
    'AZT/3TC+ATV/r' AS 'Title 13',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'AZT/3TC+ATV/r') AS 'prescribed 13',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'AZT/3TC+ATV/r') AS 'dispensed 13',
    'AZT/3TC+DTG' AS 'Title 14',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'AZT/3TC+DTG') AS 'prescribed 14',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'AZT/3TC+DTG') AS 'dispensed 14',
    'AZT/3TC+DTG+DRV/r' AS 'Title 15',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'AZT/3TC+DTG+DRV/r') AS 'prescribed 15',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'AZT/3TC+DTG+DRV/r') AS 'dispensed 15',
    'AZT/3TC+EFV' AS 'Title 16',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'AZT/3TC+EFV') AS 'prescribed 16',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'AZT/3TC+EFV') AS 'dispensed 16',
    'AZT/3TC+LPV/r' AS 'Title 17',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'AZT/3TC+LPV/r') AS 'prescribed 17',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'AZT/3TC+LPV/r') AS 'dispensed 17',
    'AZT/3TC+NVP' AS 'Title 18',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'AZT/3TC+NVP') AS 'prescribed 18',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'AZT/3TC+NVP') AS 'dispensed 18',
    'CTX' AS 'Title 19',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'CTX') AS 'prescribed 19',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'CTX') AS 'dispensed 19',
    'DRV/r' AS 'Title 20',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'DRV/r') AS 'prescribed 20',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'DRV/r') AS 'dispensed 20',
    'DTG' AS 'Title 21',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'DTG') AS 'prescribed 21',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'DTG') AS 'dispensed 21',
    'EFV' AS 'Title 22',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'EFV') AS 'prescribed 22',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'EFV') AS 'dispensed 22',
    'INH' AS 'Title 23',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'INH') AS 'prescribed 23',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'INH') AS 'dispensed 23',
    'LPV/r' AS 'Title 24',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'LPV/r') AS 'prescribed 24',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'LPV/r') AS 'dispensed 24',
    'NVP' AS 'Title 25',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'NVP') AS 'prescribed 25',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'NVP') AS 'dispensed 25',
    'TDF/3TC' AS 'Title 26',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC') AS 'prescribed 26',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC') AS 'dispensed 26',
    'TDF/3TC/DTG' AS 'Title 27',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC/DTG') AS 'prescribed 27',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC/DTG') AS 'dispensed 27',
    'TDF/3TC/EFV' AS 'Title 28',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC/EFV') AS 'prescribed 28',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC/EFV') AS 'dispensed 28',
    'TDF/3TC+ATV' AS 'Title 29',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC+ATV') AS 'prescribed 29',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC+ATV') AS 'dispensed 29',
    'TDF/3TC+ATV/r' AS 'Title 30',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC+ATV/r') AS 'prescribed 30',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC+ATV/r') AS 'dispensed 30',
    'TDF/3TC+DTG' AS 'Title 31',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC+DTG') AS 'prescribed 31',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC+DTG') AS 'dispensed 31',
    'TDF/3TC+DTG+DRV/r' AS 'Title 32',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC+DTG+DRV/r') AS 'prescribed 32',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC+DTG+DRV/r') AS 'dispensed 32',
    'TDF/3TC+EFV' AS 'Title 33',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC+EFV') AS 'prescribed 33',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC+EFV') AS 'dispensed 33',
    'TDF/3TC+LPV/r' AS 'Title 34',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC+LPV/r') AS 'prescribed 34',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC+LPV/r') AS 'dispensed 34',
    'TDF/3TC+NVP' AS 'Title 35',
    getNumberOfARVPrescribed('#startDate#','#endDate#', 'TDF/3TC+NVP') AS 'prescribed 35',
    getNumberOfARVDispensed('#startDate#','#endDate#', 'TDF/3TC+NVP') AS 'dispensed 35';