SELECT 'New positives' AS 'Title',
    Testing_Indicator7de('#startDate#','#endDate#',0,1,0,'m', 'Positive') AS '<1 years M',
    Testing_Indicator7de('#startDate#','#endDate#',0,1,0,'f', 'Positive') AS '<1 years F',
    Testing_Indicator7de('#startDate#','#endDate#',1,4,1,'m', 'Positive') AS '1 - 4 years M',
    Testing_Indicator7de('#startDate#','#endDate#',1,4,1,'f', 'Positive') AS '1 - 4 years F',
    Testing_Indicator7de('#startDate#','#endDate#',5,9,1,'m', 'Positive') AS '5 - 9 years M',
    Testing_Indicator7de('#startDate#','#endDate#',5,9,1,'f', 'Positive') AS '5 - 9 years F',
    Testing_Indicator7de('#startDate#','#endDate#',10,14,1,'m', 'Positive') AS '10-14 years M',
    Testing_Indicator7de('#startDate#','#endDate#',10,14,1,'f', 'Positive') AS '10-14 years F',
    Testing_Indicator7de('#startDate#','#endDate#',15,19,1,'m', 'Positive') AS '15-19 years M',
    Testing_Indicator7de('#startDate#','#endDate#',15,19,1,'f', 'Positive') AS '15-19 years F',
    Testing_Indicator7de('#startDate#','#endDate#',20,24,1,'m', 'Positive') AS '20-24 years M',
    Testing_Indicator7de('#startDate#','#endDate#',20,24,1,'f', 'Positive') AS '20-24 years F',
    Testing_Indicator7de('#startDate#','#endDate#',25,29,1,'m', 'Positive') AS '25-29 years M',
    Testing_Indicator7de('#startDate#','#endDate#',25,29,1,'f', 'Positive') AS '25-29 years F',
    Testing_Indicator7de('#startDate#','#endDate#',30,34,1,'m', 'Positive') AS '30-34 years M',
    Testing_Indicator7de('#startDate#','#endDate#',30,34,1,'f', 'Positive') AS '30-34 years F',
    Testing_Indicator7de('#startDate#','#endDate#',35,39,1,'m', 'Positive') AS '35-39 years M',
    Testing_Indicator7de('#startDate#','#endDate#',35,39,1,'f', 'Positive') AS '35-39 years F',
    Testing_Indicator7de('#startDate#','#endDate#',40,44,1,'m', 'Positive') AS '40-44 years M',
    Testing_Indicator7de('#startDate#','#endDate#',40,44,1,'f', 'Positive') AS '40-44 years F',
    Testing_Indicator7de('#startDate#','#endDate#',45,49,1,'m', 'Positive') AS '45-49 years M',
    Testing_Indicator7de('#startDate#','#endDate#',45,49,1,'f', 'Positive') AS '45-49 years F',
    Testing_Indicator7de('#startDate#','#endDate#',50,200,1,'m', 'Positive') AS '>=50 years M',
    Testing_Indicator7de('#startDate#','#endDate#',50,200,1,'f', 'Positive') AS '>=50 years F',
    0 AS 'Unknown Age M',
    0 AS 'Unknown Age F';