SELECT
    " " as "baselineCode",
    " " as "refline",
    " " as "transDate",
    getPatientARTNumber(p.patient_id) as "ARTCode",
    getObsCodedValueInSectionByNames(p.patient_id, "Screened", "TB Form") as "TBScreening",
    getFirstARVPrescribed(p.patient_id) as "prevRegimen",
    getObsCodedValueInSectionByNames(p.patient_id, "Last ARV Protocol for the previous month", "Treatment Modification") as "PrevTreatmentLine",
    getPatientMostRecentProgramAttributeCodedValue(p.patient_id, "397b7bc7-13ca-4e4e-abc3-bf854904dce3", "en") as "treatmentLine",
    getListOfActiveARVDrugs(p.patient_id, "#startDate#", "#endDate#") as "ARVRegimen",
    getDateOfVLEligibility(p.patient_id) as "eligibilityDate",
    getViralLoadTestDate(p.patient_id) as "sampleCollectionDate",
    getViralLoadTestResult(p.patient_id) as "result",
    getNextAppointmentDate(p.patient_id) BETWEEN "#startDate#" AND "#endDate#" as "nextAppointmentDate",
    " " as "siteCode",
    IF(patientWasPrescribedARVDrugDuringReportingPeriod(p.patient_id, "#startDate#", "#endDate#"), "01", "02") as "ARTConso",
    " " as "DStatus",
    IF(getProgramAttributeValueWithinReportingPeriod(p.patient_id, "#startDate#", "#endDate#", "242c9027-dc2d-42e6-869e-045e8a8b95cb", "HIV_PROGRAM_KEY")="true","Yes","No") as "breastFeeding",
    getVLSuppressedOrUnsuppressed(p.patient_id) as "viralLoadStatus",
    getViralLoadTestDate(p.patient_id) as "resultDate",
    getDateLatestVLResultShared(p.patient_id) as "sampleSentToLabDate",
    " " as "resultType",
    getViralLoadTestDate(p.patient_id) as "dateOfResultsReception",
    " " as "ANCReference",
    getReasonLastVLExam(p.patient_id) as "VLReason",
    patientHasEnrolledIntoEACProgram(p.patient_id) as "isClientEnrolledOnEAC",
    (getObsCodedValue(p.patient_id, "32adf7f8-2ca0-4e35-b9b5-e68522f7bab0") = "Switch to the next line ART") as "isClientSwitchedToNextLine",
    (getObsCodedValue(p.patient_id, "1a32273b-f99e-402d-af70-062f09963dc8") = "Resistance Reported") as "testOfResistance",
    (getObsCodedValue(p.patient_id, "1a32273b-f99e-402d-af70-062f09963dc8") = "No Resistance Reported") as "noResistanceReported",
    " " as "resistanceAccordingToMoleculesIdentified",
    getObsCodedValue(p.patient_id, "80472b4d-e37b-46c9-9078-85e3a509af24") as "EACSessions",
    IF(getObsCodedValue(p.patient_id, "80472b4d-e37b-46c9-9078-85e3a509af24") LIKE "%Ext EAC 1", "Ext EAC 2", "Ext EAC 3") as "extendedEACSessions",
    " " as "EACClassification",
    " " as "viralLoadRequestDate",
    " " as "isAnEACDefaulter",
    " " as "previousRegimenId",
    " " as "regimenId",
    " " as "isPregnantBool",
    " " as "wasSampleCollectedInHealthFacility",
    " " as "viralLoadOrderId",
    " " as "syncDate",
    " " as "viralLoadRejectionReason"
FROM patient p,(SELECT @a:= 0) AS a
WHERE
  patientHasEnrolledIntoHivProgramDuringReportingPeriod(p.patient_id, "#startDate#", "#endDate#");
