SELECT 'Malnutrition' AS 'Title',
    Testing_Indicator1('#startDate#','#endDate#',0,1,0,'m','Positive','Malnutrition') AS '<1 years M Pos',
    Testing_Indicator1('#startDate#','#endDate#',0,1,0,'f','Positive','Malnutrition') AS '<1 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',1,4,1,'m','Positive','Malnutrition') AS '1 - 4 years M Pos',
    Testing_Indicator1('#startDate#','#endDate#',1,4,1,'f','Positive','Malnutrition') AS '1 - 4 years F Pos',   
    Testing_Indicator1('#startDate#','#endDate#',5,9,1,'m','Positive','Malnutrition') AS '5 - 9 years M Pos',
    Testing_Indicator1('#startDate#','#endDate#',5,9,1,'f','Positive','Malnutrition') AS '5 - 9 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',10,14,1,'m','Positive','Malnutrition') AS '10-14 years M Pos',
    Testing_Indicator1('#startDate#','#endDate#',10,14,1,'f','Positive','Malnutrition') AS '10-14 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',0,1,0,'m','Negative','Malnutrition') AS '<1 years M Neg',
    Testing_Indicator1('#startDate#','#endDate#',0,1,0,'f','Negative','Malnutrition') AS '<1 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',1,4,1,'m','Negative','Malnutrition') AS '1 - 4 years M Neg',
    Testing_Indicator1('#startDate#','#endDate#',1,4,1,'f','Negative','Malnutrition') AS '1 - 4 years F Neg',   
    Testing_Indicator1('#startDate#','#endDate#',5,9,1,'m','Negative','Malnutrition') AS '5 - 9 years M Neg',
    Testing_Indicator1('#startDate#','#endDate#',5,9,1,'f','Negative','Malnutrition') AS '5 - 9 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',10,14,1,'m','Negative','Malnutrition') AS '10-14 years M Neg',
    Testing_Indicator1('#startDate#','#endDate#',10,14,1,'f','Negative','Malnutrition') AS '10-14 years F Neg';