SELECT 'PMTCT [ANC1-Only]' AS 'Title',
    Testing_Indicator1('#startDate#','#endDate#',0,1,0,'f','Positive','PMTCT [ANC1-Only]') AS '<1 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',1,4,1,'f','Positive','PMTCT [ANC1-Only]') AS '1 - 4 years F Pos',   
    Testing_Indicator1('#startDate#','#endDate#',5,9,1,'f','Positive','PMTCT [ANC1-Only]') AS '5 - 9 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',10,14,1,'f','Positive','PMTCT [ANC1-Only]') AS '10-14 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',15,19,1,'f','Positive','PMTCT [ANC1-Only]') AS '15-19 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',20,24,1,'f','Positive','PMTCT [ANC1-Only]') AS '20-24 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',25,29,1,'f','Positive','PMTCT [ANC1-Only]') AS '25-29 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',30,34,1,'f','Positive','PMTCT [ANC1-Only]') AS '30-34 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',35,39,1,'f','Positive','PMTCT [ANC1-Only]') AS '35-39 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',40,44,1,'f','Positive','PMTCT [ANC1-Only]') AS '40-44 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',45,49,1,'f','Positive','PMTCT [ANC1-Only]') AS '45-49 years F Pos',
    Testing_Indicator1('#startDate#','#endDate#',50,200,1,'f','Positive','PMTCT [ANC1-Only]') AS '>=50 years F Pos',
    0 AS 'Unknown Age F Pos',
    Testing_Indicator1('#startDate#','#endDate#',0,1,0,'f','Negative','PMTCT [ANC1-Only]') AS '<1 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',1,4,1,'f','Negative','PMTCT [ANC1-Only]') AS '1 - 4 years F Neg',   
    Testing_Indicator1('#startDate#','#endDate#',5,9,1,'f','Negative','PMTCT [ANC1-Only]') AS '5 - 9 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',10,14,1,'f','Negative','PMTCT [ANC1-Only]') AS '10-14 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',15,19,1,'f','Negative','PMTCT [ANC1-Only]') AS '15-19 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',20,24,1,'f','Negative','PMTCT [ANC1-Only]') AS '20-24 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',25,29,1,'f','Negative','PMTCT [ANC1-Only]') AS '25-29 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',30,34,1,'f','Negative','PMTCT [ANC1-Only]') AS '30-34 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',35,39,1,'f','Negative','PMTCT [ANC1-Only]') AS '35-39 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',40,44,1,'f','Negative','PMTCT [ANC1-Only]') AS '40-44 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',45,49,1,'f','Negative','PMTCT [ANC1-Only]') AS '45-49 years F Neg',
    Testing_Indicator1('#startDate#','#endDate#',50,200,1,'f','Negative','PMTCT [ANC1-Only]') AS '>=50 years F Neg',
    0 AS 'Unknown Age F Neg';