SELECT
    getPatientARTNumber(p.patient_id) as "ArtCode",
    getPatientARTNumber(p.patient_id) as "ExistingArtCode",
    CAST(@a:=@a+1 AS CHAR) as "serialNumber",
    getPatientARVStartDate(p.patient_id) as "ArtStartDate",
    DATE(getProgramAttributeValueWithinReportingPeriod(p.patient_id, "2000-01-01","2100-01-01", "2dc1aafd-a708-11e6-91e9-0800270d80ce", "HIV_PROGRAM_KEY")) as "eligibilityCriteria",
    CONCAT(getPatientVillage(p.patient_id),",",getPatientPreciseLocation(p.patient_id)) as "address",
    getPatientOccupation(p.patient_id) as "profession",
    getPatientPhoneNumber(p.patient_id) as "contactTelephone",
    getPatientGender(p.patient_id) as "sex",
    getPatientBirthdate(p.patient_id) as "birthDate",
    getObsNumericValue(p.patient_id,"5089AAAAAAAAAAAAAAAAAAAAAAAAAAAA") as "Weight(Kg)",
    getObsNumericValue(p.patient_id,"5090AAAAAAAAAAAAAAAAAAAAAAAAAAAA") as "Height(Cm)",
    getObsNumericValue(p.patient_id,"c367d9ee-3f10-11e4-adec-0800271c1b75") as "BMI",
    getPatientMostRecentProgramTrackingStateValue(p.patient_id,"en","IPT_PROGRAM_KEY") as "IPT Clinical Stage",
    getObsNumericValue(p.patient_id,"84af6048-592a-433f-be20-18c9594fcb3f") as "PregnancyAge",
    " " AS "Child",
    " " AS "feeding Option",
    IF(getObsCodedValue(p.patient_id, "f0447183-d13f-463d-ad0f-1f45b99d97cc") LIKE "Yes%", "Yes", "No") as "TB Screening",
    " " AS "inhStartDate",
    " " AS "inhStopDate",
    " " AS "TBTheraphyStartDate",
    " " AS "TBTheraphyStopDate",
    " " AS "ViralHepatites",
    " " AS "ViralHepatitesType",
    " " AS "ARTConso",
    " " AS "CD4Date",
    " " AS "TestedInThisFacility",
    " " AS "DateOfTest",
    " " AS "IsTransferredIn",
    " " AS "KPType",
    " " AS "WasPatientRetested",
    " " AS "IsPregnant",
    " " AS "PriorityPopulation",
    " " AS "PriorityPopulationType",
    " " AS "DisclosureStatus",
    " " AS "DisclosureType",
    " " AS "IsRestarted",
    " " AS "DoYouHaveChildren",
    " " AS "MaritalStatus",
    " " AS "NumberOfChildrenInCharge",
    " " AS "AgeOfLastChild",
    " " AS "LevelOfStudies",
    " " AS "PartnerWasInformed",
    " " AS "PartnerStatus",
    " " AS "NumberOfSexualPartners",
    " " AS "STI",
    " " AS "NIC",
    " " AS "UHCCode",
    " " AS "HPStartDate",
    " " AS "HPEndDate",
    " " AS "TreatmentLine"

FROM patient p, (SELECT @a:= 0) AS a
WHERE
    patientHasStartedARVTreatmentDuringReportingPeriod(p.patient_id, "#startDate#", "#endDate#");