SELECT
    "NULL" AS "BaselineCode",
    uuid() AS "Reference",
    getObsDatetimeValue(p.patient_id, "1d4a6dc4-c478-4021-982b-62e3c84f7857") AS "RegistrationDate",
    CAST(@a:=@a+1 AS CHAR) AS "DTCNumber",
    CONCAT(pn.given_name, ' ', pn.family_name) AS "PatientName",
    getPatientGender(p.patient_id) AS "Sex",
    CONCAT(getPatientVillage(p.patient_id),", ",getPatientPreciseLocation(p.patient_id)) AS "Address",
    getPatientBirthdate(p.patient_id) AS "DateOfBirth",
    "NULL" AS "SiteCode",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_2_PATIENT_TREATMENT_DATE", "TB_PROGRAM_KEY") AS "TreatmentStartDate",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_5_PATIENT_STAGE", "TB_PROGRAM_KEY") AS "TreatmentCategory",
    getObsCodedValueInSectionByNames(p.patient_id,"Disease site","Case Definition") AS "DiseaseSite",
    getObsCodedValueInSectionByNames(p.patient_id,"WHO registration group","Case Definition") AS "PatientType",
    getObsCodedValueInSectionByNames(p.patient_id,"Drug resistance profile","Case Definition") AS "RRT",
    "NULL" AS "Transfer",
    "NULL" AS "MBeforeTreatment",
    getObsDatetimeValue(p.patient_id, "f79780e8-72de-4162-be89-dd908ab2e5bb") AS "TestDateBeforeTreatment",
    "NULL" AS "M2Months",
    "NULL" AS "TestDate2Months",
    "NULL" AS "M5Months",
    "NULL" AS "TestDate5Months",
    "NULL" AS "MEndOfTreatment",
    "NULL" AS "TestDateEndOfTreatment",
    getPatientMostRecentProgramOutcome(p.patient_id, "en", "TB_PROGRAM_KEY") AS "TreatmentOutcome",
    "NULL" AS "DateOfResults",
    getObsCodedValueInSectionByNames(p.patient_id,"HTC, Result if tested","HIV Testing and Counseling Intake Template") AS "SerologyResultsPrior",
    getObsCodedValueInSectionByNames(p.patient_id,"Final Test Result","Final Result") AS "SerologyResults",
    IF(getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_2_PATIENT_TREATMENT_DATE", "HIV_PROGRAM_KEY")) AS "ARV"
    

FROM patient p JOIN person_name pn ON pn.person_id = p.patient_id,
 (SELECT @a:= 0) AS a
-- WHERE
    -- patientHasStartedARVTreatmentDuringReportingPeriod(p.patient_id, "#startDate#", "#endDate#");



    
    
    
    
    
    
    
    
    
    
    
--     CAST(@a:=@a+1 AS CHAR) as "LAB01",
--     "NULL" as "LAB02",
--     CONCAT(pn.given_name, ' ', pn.family_name) as "LAB03",
--     CONCAT(getPatientVillage(p.patient_id),",",getPatientPreciseLocation(p.patient_id)) as "LAB04",
--     getPatientBirthdate(p.patient_id) as "BIRTHDATE",
--     getPatientGender(p.patient_id) as "LAB05A",
--     "NULL" as "LAB06",
--     getPatientPhoneNumber(p.patient_id) as "LAB07",
--     getPatientEntryPointAndModality(p.patient_id) as "LAB08",
--     getPatientHIVFinalTestResult(p.patient_id) as "LAB09A",
--     getPatientHIVFinalTestResult(p.patient_id) as "LAB09B",
--     getObsCodedValueInSectionByNames(p.patient_id,"Final Result Test 1","First Test")  as "LAB10A",
--     getObsCodedValueInSectionByNames(p.patient_id,"Final Result Test 2","Second Test") as "LAB10B",
--     "NULL" as "LAB10C",
--     getObsCodedValueInSectionByNames(p.patient_id,"Final Test Result","Final Result") as "LAB11",
--     "NULL" as "LAB14",
--     "NULL" as "LAB15",
--     getObsNumericValue(p.patient_id, '7f4ac69f-a091-45c2-9972-70e2511a01f5') as "LAB16",
--     getViralLoadTestResult(p.patient_id) as "LAB17",
--     getNumericLabTestResult(p.patient_id,4207) as "LAB18",
--     getNumericLabTestResult(p.patient_id,3543) as "LAB19",
--     "NULL" as "LAB20",
--     getNumericLabTestResult(p.patient_id,4252) as "LAB21",
--     "NULL" as "LAB22",
--     "NULL" as "LAB23",
--     getObsCodedValueInSectionByNames(p.patient_id,"Albumin (Urine)","Laboratory tests and results") as "LAB24",
--     "NULL" as "LAB25",
--     getObsCodedValueInSectionByNames(p.patient_id,"Blood Group","Current Pregnancy") as "LAB26A",
--     "NULL" as "LAB26B",
--     "NULL" as "LAB27",
--     "NULL" as "LAB28",
--     "NULL" as "LAB29",
--     "NULL" as "LAB30",
--     "NULL" as "LAB31",
--     "NULL" as "LAB32",                       
--     "NULL" as "LAB33A1",
--     "NULL" as "LAB33B1",
--     "NULL" as "LAB33A2",
--     "NULL" as "LAB33B2",
--     "NULL" as "LAB34",
--     "NULL" as "LAB35",
--     "NULL" as "LAB36",
--     "NULL" as "LAB37",
--     "NULL" as "LAB38",
--     "NULL" as "LAB39",
--     "NULL" as "LAB40",
--     "NULL" as "SiteCode",
--     "NULL" as "LABConso", 
--     "NULL" as "LABDate",
--     getPatientEntryPointAndModality(p.patient_id) as "LAB08F",
--     "NULL" as "EPU",
--     "NULL" as "DStatus",
--     "NULL" as "DatimEntryPoint",
--     "NULL" as "SoureRegisterReference",
--     "NULL" as "RegisterType",
--     getPatientMostRecentProgramOutcome(p.patient_id, "en", "HIV_PROGRAM_KEY") as "WasPatientInitiated",
--    "NULL" as "BaselinReference",
--     getObsCodedValueInSectionByNames(p.patient_id,"HTC, Result", "2nd HIV Test (for women with HIV negative test >3mo old)") as "FirstReTesting",
--     getObsCodedValueInSectionByNames(p.patient_id,"HTC, Result", "2nd HIV Test (for women with HIV negative test >3mo old)") as "SecondReTesting",
--     getObsCodedValueInSectionByNames(p.patient_id,"HTC, Result", "2nd HIV Test (for women with HIV negative test >3mo old)") as "ThirdRetesting",
--     getObsCodedValueInSectionByNames(p.patient_id,"Repeat Test Result", "2nd HIV Test (for women with HIV negative test >3mo old)") as "FinalRetesting",
--     "NULL" as "ReasonsForNotInitiatingPatient",
--     "NULL" as "OtherReasonsForNotInitiatingPatient",  
--     "NULL" as "CounselorTesterCode",
--     "NULL" as "CounselorReTesterCode",
--     getObsCodedValuesInNestedSectionByNames(p.patient_id,"Kit Name","First Test", "HIV Test 1") as "ServiceOrderReferencekit1",
--     getObsCodedValuesInNestedSectionByNames(p.patient_id,"Kit Name","First Test","HIV Test 2") as "ServiceOrderReferencekit2",
--     "NULL" as "ServiceOrderReferenceKit3",                       
--     getObsCodedValuesInNestedSectionByNames(p.patient_id,"Kit Name","Second Test", "HIV Test 1") as "RetestServiceOrderReferencekit1",
--     getObsCodedValuesInNestedSectionByNames(p.patient_id,"Kit Name","Second Test", "HIV Test 2") as "RetestServiceOrderReferencekit2",
--     "NULL" as "RetestServiceOrderReferencek",
--     "NULL" as "TestMark",
--     "NULL" as "RetestMark",
--     getObsCodedValueInSectionByNames(p.patient_id,"Priority population type","HTC, Pre-test Counseling Set") as "PriorityPopulation",
--     getObsCodedValueInSectionByNames(p.patient_id,"Priority population type","HTC, Pre-test Counseling Set") as "PriorityPopulationType",
--     "NULL" as "TargetedTestingEligibility",
--     getPatientEntryPointAndModality(p.patient_id) as "ClientReceivedInFacility",
--     getPatientOccupation(p.patient_id) as "profession",
--     getPatientCNINumber(patient_id) as 'NIC',
--     getObsCodedValue(p.patient_id, "248e21db-98f8-49fc-b596-fe9042b013ac") as "KPType",
--     "NULL" as "HTSRecentResult", 
--     IF(getProgramAttributeValueWithinReportingPeriod(p.patient_id, "#startDate#", "#endDate#", "242c9027-dc2d-42e6-869e-045e8a8b95cb", "HIV_PROGRAM_KEY")="true","Yes","No") as "IsBreastFeeding",
--     "NULL" as "RTAClassification",
--     IF(getObsCodedValueInSectionByNames(p.patient_id,"HTC, Result if tested","HIV Testing and Counseling Intake Template") LIKE "Positive%", "Yes", "No") as "KnownHIVCase",
--     "NULL" as "DestinationFacilityCode",
--     "NULL" as "ClientOutCode",
--     getViralLoadTestDate(p.patient_id) as "BlineReference",
--     "NULL" as "DateAdded",
--     "NULL" as "LastChangeDate",
--     "NULL" as "LastChangedBy"




    
