SELECT
    "NULL" AS "BaselineCode",
    uuid() AS "Reference",
    getObsDatetimeValue(p.patient_id, "1d4a6dc4-c478-4021-982b-62e3c84f7857") AS "RegistrationDate",
    CAST(@a:=@a+1 AS CHAR) AS "DTCNumber",
    CONCAT(pn.given_name, ' ', pn.family_name) AS "PatientName",
    getPatientGender(p.patient_id) AS "Sex",
    CONCAT(getPatientVillage(p.patient_id),", ",getPatientPreciseLocation(p.patient_id)) AS "Address",
    getPatientBirthdate(p.patient_id) AS "DateOfBirth",
    "NULL" AS "SiteCode",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_2_PATIENT_TREATMENT_DATE", "TB_PROGRAM_KEY") AS "TreatmentStartDate",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_5_PATIENT_STAGE", "TB_PROGRAM_KEY") AS "TreatmentCategory",
    getObsCodedValueInSectionByNames(p.patient_id,"Disease site","Case Definition") AS "DiseaseSite",
    getObsCodedValueInSectionByNames(p.patient_id,"WHO registration group","Case Definition") AS "PatientType",
    getObsCodedValueInSectionByNames(p.patient_id,"Drug resistance profile","Case Definition") AS "RRT",
    "NULL" AS "Transfer",
    "NULL" AS "MBeforeTreatment",
    "NULL" AS "XBeforeTreatment",
    getObsDatetimeValue(p.patient_id, "f79780e8-72de-4162-be89-dd908ab2e5bb") AS "TestDateBeforeTreatment",
    "NULL" AS "M2Months",
    "NULL" AS "TestDate2Months",
    "NULL" AS "M5Months",
    "NULL" AS "TestDate5Months",
    "NULL" AS "MEndOfTreatment",
    "NULL" AS "TestDateEndOfTreatment",
    getPatientMostRecentProgramOutcome(p.patient_id, "en", "TB_PROGRAM_KEY") AS "TreatmentOutcome",
    "NULL" AS "DateOfResults",
    getObsCodedValueInSectionByNames(p.patient_id,"HTC, Result if tested","HIV Testing and Counseling Intake Template") AS "SerologyResultsPrior",
    getObsCodedValueInSectionByNames(p.patient_id,"Final Test Result","Final Result") AS "SerologyResults",
    getObsCodedValueInSectionByNames(p.patient_id,"Cotrimoxazole prophylaxis","2. Prophylaxis") AS "Cotrimoxazole",
    -- IF(getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_2_PATIENT_TREATMENT_DATE", "HIV_PROGRAM_KEY")) AS "ARV"
    "NULL" AS "Observations",
    "NULL" AS "X2Months",
    "NULL" AS "X5Months",
    "NULL" AS "XEndOfTreatment",
    getPatientPhoneNumber(p.patient_id) AS "PhoneNumber",
    getPatientEntryPointAndModality(p.patient_id) AS "EntryPoint",
    getObsDatetimeValue(p.patient_id, "c6c08cdc-18dc-4f42-809c-959621bc9a6c") AS "SerologyTestDatePrior",
    "NULL" AS "MBeforeTreatmentOneToNineValue",
    "NULL" AS "M5MonthsOneToNineValue",
    getObsCodedValueInSectionByNames(p.patient_id,"Final Result Test 1","First Test") AS "TestResult1",
    getObsCodedValueInSectionByNames(p.patient_id,"Final Result Test 2","Second Test") AS "TestResult2",
    "NULL" AS "TestResult3",
    getObsCodedValuesInNestedSectionByNames(p.patient_id,"Kit Name","First Test", "HIV Test 1") AS "ServiceOrderReferenceKit1",
    getObsCodedValuesInNestedSectionByNames(p.patient_id,"Kit Name","Second Test", "HIV Test 1") AS "ServiceOrderReferenceKit2",
    "NULL" AS "ServiceOrderReferenceKit3",
    "NULL" AS "TestingCounselorCode",
    getObsCodedValueInSectionByNames(p.patient_id,"Priority population type","HTC, Pre-test Counseling Set") AS "PriorityPopulation",
    getObsCodedValueInSectionByNames(p.patient_id,"Priority population type","HTC, Pre-test Counseling Set") AS "PriorityPopulationType",
    getObsCodedValue(p.patient_id, "9edf4f7c-9baf-4467-80b8-45440406ebfb") AS "TargetedTestingEligibility",
    "NULL" AS "ClientReceivedInFacility",
    getPatientOccupation(p.patient_id) AS "Profession",
    getPatientCNINumber(patient_id) as 'NIC',
    getObsCodedValue(p.patient_id, "248e21db-98f8-49fc-b596-fe9042b013ac") as "KPType",
    "NULL" AS "HTSRecentResult",
    "NULL" AS "RITAClassification",
    IF(getObsCodedValueInSectionByNames(p.patient_id,"HTC, Result if tested","HIV Testing and Counseling Intake Template") LIKE "Positive%", "Yes", "No") as "KnownHIVCase",
    "NULL" AS "RHEZ",
    "NULL" AS "RH",
    "NULL" AS "WasTestedForHTSRecentViralLoad",
    "NULL" AS "SyncDate"

FROM patient p JOIN person_name pn ON pn.person_id = p.patient_id,
 (SELECT @a:= 0) AS a
WHERE
    patientHasEnrolledIntoTBProgramDuringReportingPeriod(p.patient_id, "#startDate#", "#endDate#");
