SELECT
    getPatientFullName(p.patient_id) as "name",
    getRelationshipNameBetweenPatients(p.patient_id, p.patient_id) as "relationWithIndex",
    getPatientPhoneNumber(p.patient_id) as "contactTelephone",
    getPatientBirthdate(p.patient_id) as "birthDate",
    getPatientGender(p.patient_id) as "sex",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_2_NOTIFICATION_DATE", "INDEX_TESTING_PROGRAM_KEY") as "notificationDate",
    " " as "testDate",
    getObsCodedValue(p.patient_id, "bc43179d-00b4-4712-a5d6-4dabd4230888") as "placeOfTest",
    getObsCodedValue(p.patient_id, "41e48d08-2235-47d5-af12-87a009057603") as "testResult",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_2_PATIENT_TREATMENT_DATE", "HIV_PROGRAM_KEY") as "dateOfInitiation",
    getPatientARTNumber(p.patient_id) as "ARTCode",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_4_CONTACT_TRACER", "INDEX_TESTING_PROGRAM_KEY") as "contactTracer",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_5_COMMENTS", "INDEX_TESTING_PROGRAM_KEY") as "comment",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_1_NOTIFICATION_METHOD", "INDEX_TESTING_PROGRAM_KEY") as "notificationMeans",
    getObsCodedValue(p.patient_id, "41e48d08-2235-47d5-af12-87a009057603") as "HIVStatus",
    " " as "siteCode",
    CAST(@a:=@a+1 AS CHAR) as "serialNumber",
    getProgramAttributeDateValueFromAttributeAndProgramName(p.patient_id, "PROGRAM_MANAGEMENT_3_NOTIFICATION_OUTCOME", "INDEX_TESTING_PROGRAM_KEY") as "NotificationOutcome",
    getObsCodedValue(p.patient_id, "659ed086-730d-4ac4-910e-fea4c6507512") as "priorTestResult",
    getObsCodedValue(p.patient_id, "f8f78cc6-8453-416a-ade2-237d67a59829") as "priorTestDone",
    getObsDatetimeValue(p.patient_id, "c6c08cdc-18dc-4f42-809c-959621bc9a6c") as "priorTestDate",
    getPatientMostRecentProgramOutcome(p.patient_id, "en", "HIV_PROGRAM_KEY") as "ARTOutcome",
    " " as "indexSiteCode",
    getObsCodedValue(p.patient_id, "bc43179d-00b4-4712-a5d6-4dabd4230888") as "entryPoint",
    getPatientDateOfEnrolmentInProgram(p.patient_id, "INDEX_TESTING_PROGRAM_KEY")  as "dateElicited",
    " " as "testingCounselorCode",
    " " as "placeOfInitiation",
    " " as "mothersStatus",
    " " as "baselineCode",
    getObsCodedValuesInNestedSectionByNames(p.patient_id, "Result", "First Test", "HIV Test 1") as "testResult1",
    getObsCodedValuesInNestedSectionByNames(p.patient_id, "Result", "First Test", "HIV Test 2") as "testResult2",
    getObsCodedValuesInNestedSectionByNames(p.patient_id, "Result", "Second Test", "HIV Test 1") as "testResult3",
    getObsCodedValuesInNestedSectionByNames(p.patient_id,"Kit Name","First Test", "HIV Test 1") as "serviceOrderReferenceKit1",
    getObsCodedValuesInNestedSectionByNames(p.patient_id,"Kit Name","First Test","HIV Test 2") as "serviceOrderReferenceKit2",
    getObsCodedValuesInNestedSectionByNames(p.patient_id,"Kit Name","Second Test","HIV Test 1") as "serviceOrderReferenceKit3",
    " " as "remark",
    " " as "isIDP",
    getObsCodedValue(p.patient_id, "5b2e5a44-b55b-4436-9948-67143841ee27") as "priorityPopulation",
    getObsCodedValue(p.patient_id, "1e7d0c45-be70-4424-a0fc-e4f391b28e9c") as "priorityPopulationType",
    " " as "targetedTestingEligibility",
    " " as "clientReceivedInFacility",
    " " as "IPVScreened",
    " " as "IPVRiskAssessmentOutcome",
    " " as "profession",
    getPatientCNINumber(patient_id) as "NIC",
    getObsCodedValue(p.patient_id, "44861d4c-de67-4368-b5cf-279b754e5343") as "kpType",
    getObsCodedValue(p.patient_id, "659ed086-730d-4ac4-910e-fea4c6507512") as "htsRecentResult",
    " " as "ritaClassification",
    IF(getProgramAttributeValueWithinReportingPeriod(p.patient_id, "#startDate#", "#endDate#", "242c9027-dc2d-42e6-869e-045e8a8b95cb", "HIV_PROGRAM_KEY")="true","Yes","No") as "isBreastFeeding",
    getObsCodedValue(p.patient_id, "659ed086-730d-4ac4-910e-fea4c6507512") = "Positive" as "knownHIVCase",
    " " as "wasTestedForHTSRecentViralLoad",
    " " as "syncDate"
FROM patient p,(SELECT @a:= 0) AS a
WHERE
  getPatientDateOfEnrolmentInProgram(p.patient_id, "INDEX_TESTING_PROGRAM_KEY") BETWEEN "#startDate#" AND "#endDate#";
