
    SELECT
    CAST(@a:=@a+1 AS CHAR) as "Serial Number",
    getPatientARTNumber(p.patient_id) as "ART Code",
    getFacilityName() as "Facility Name",
    getPatientIdentifier(p.patient_id) as "Patient ID",
    patientAgeAtHivEnrollment(p.patient_id) as "Age At Enrollment",
    getPatientBirthdate(p.patient_id) as "Date of birth",
    getPatientGender(p.patient_id) as "Sex",
    pi.identifier as "Patient Identifier",
    getPatientHIVTestDate(p.patient_id) as "HIV Test Date",
    getPatientARVStartDate(p.patient_id) as "Date of ARV initiation",
    CONCAT(getPatientVillage(p.patient_id),",",getPatientPreciseLocation(p.patient_id)) as "Address",
    getPatientPhoneNumber(p.patient_id) as "Contact telephone",
    getPatientMostRecentProgramTrackingStateValue(p.patient_id,"en","HIV_PROGRAM_KEY") as "Clinical Who Stage",
    getARVTherapeuticLineAtInitiation(p.patient_id) as "line At Initiation",
    getFirstARVPrescribed(p.patient_id) as "Regimen at ART Initiation", 
	getActiveARVWithLowestDispensationPeriod(p.patient_id, '#startDate#', '#endDate#') as "Current ART Regimen",
	getPatientMostRecentProgramAttributeCodedValue(p.patient_id, "397b7bc7-13ca-4e4e-abc3-bf854904dce3", "en") as "Current Regimen Line",
    getPregnancyStatus(p.patient_id) as "Patient is Pregnant",
    IF(getProgramAttributeValueWithinReportingPeriod(p.patient_id, "#startDate#", "#endDate#", "242c9027-dc2d-42e6-869e-045e8a8b95cb", "HIV_PROGRAM_KEY")="true","Yes","No") as "Patient is Breastfeeding",
    IF(getObsCodedValue(p.patient_id, "f0447183-d13f-463d-ad0f-1f45b99d97cc") LIKE "Yes%", "Yes", "No") as "TB Screening",
    getTBScreeningStatus(p.patient_id) as "TB Screening Result",
    IF(patientHasBeenPrescribedDrug(p.patient_id, "INH","#startDate#", "#endDate#"),"Yes","No") as "INH",
    getPatientTBStartDate(p.patient_id) as "TB program Start Date",
    getLastArvStartDate(p.patient_id, "2000-01-01", "#endDate#") as "Last Dispensed ARV Start Date",
    patientLatestArvDrugWasDispensed(p.patient_id) as "Last Drug Dispensed",
    getDurationMostRecentArvTreatmentInDays(p.patient_id,"2000-01-01", "#endDate#") as "Number of Days Dispensed",
    getPatientMostRecentProgramAttributeCodedValue(p.patient_id, "39202f47-a709-11e6-91e9-0800270d80ce", "en") as "Reason For Initiation",
    IF(patientHasProgramOutcomeTransferredOutWithinReportingPeriod(p.patient_id, "#startDate#", "#endDate#") = 1, "yes", "no") as "Transfered Out But receiving drug",
    IF(getObsCodedValue(p.patient_id, "211f0857-61a3-4049-9777-374c4a592453") IS NOT NULL, "True", "False") as "KP",
    getObsCodedValue(p.patient_id, "211f0857-61a3-4049-9777-374c4a592453") as "KP Type",
    patientHasEnrolledIntoHivProgram(p.patient_id) as "Enrolled into HIV Program?",
    arvInitiationDateSpecified(p.patient_id) as "ARV Initiation Date Specified?",
    patientHasAtLeastOneArvDrugPrescribed(p.patient_id) as "Has at least one ARV drug prescribed?",
    patientLatestArvDrugWasDispensed(p.patient_id) as "Latest ARV drug was dispensed?",
    patientTherapeuticLineSpecified(p.patient_id) as "Therapeutic Line Specified?",
    patientHasScheduledAnAppointmentDuringReportingPeriod(p.patient_id,"#startDate#","#endDate#","APPOINTMENT_SERVICE_ART_KEY") as "ART Appointment Scheduled?",
    patientHasScheduledAnAppointmentDuringReportingPeriod(p.patient_id,"#startDate#","#endDate#","APPOINTMENT_SERVICE_ART_DISPENSARY_KEY") as "ART Dispensary Appointment Scheduled?",
    getPatientEntryPointAndModality(p.patient_id) as "Testing Entry Point and Modality Specified?",
    getPatientInformedConsent(p.patient_id) as "Informed Consent Specified?",
    getPatientHIVTestDate(p.patient_id) as "HIV Test Date Specified?",
    getPatientHIVFinalTestResult(p.patient_id) as "Final Test Result Specified?",
    getPatientIndexTestingOffered(p.patient_id) as "Index Testing offered?",
    getPatientIndexTestingAccepted(p.patient_id) as "Index Testing Accepted?",
    patientHadALeastOneViralLoadExam(p.patient_id) as "Viral Load Exam Done?",
    getViralLoadTestDate(p.patient_id) as "Last Viral Load Result Date",
    getViralLoadTestResult(p.patient_id) as "Last Viral Load Result",
    getReasonLastVLExam(p.patient_id) as "Reason Of Last Viral Load"

FROM patient p
JOIN person_name pn ON pn.person_id = p.patient_id
JOIN patient_identifier pi ON pi.patient_id = p.patient_id
JOIN person per ON per.person_id = p.patient_id
WHERE isFormFilledWithinReportingPeriod(p.patient_id, 'c10a9ed0-1992-4118-8f6f-2311663f2bc2', "#startDate#", "#endDate#") = 1
GROUP BY p.patient_id;