SELECT
    getPatientARTNumber(p.patient_id) as "baselineCode",
    " " as "refline",
    " " as "transDate",
    getPatientARTNumber(p.patient_id) as "ARTCode",
    " " as "TBScreening",
    getObsCodedValueInSectionByNames(p.patient_id, "Last ARV Protocol for the previous month", "Treatment Modification") as "prevTreatmentLine",
    " " as "treatmentLine",
    getObsCodedValueInSectionByNames(p.patient_id, "Cotrimoxazole prophylaxis", "Prophylaxis") as "cotrimoxazole",
    " " as "patientStatus",
    getNextAppointmentDate(p.patient_id) as "nextAppointmentDate",
    " " as "siteCode",
    " " as "ARTConso",
    getObsCodedValueInSectionByNames(p.patient_id, "Reason for Change in Treatment", "Treatment Modification") as "substitutionReason",
    " " as "DStatus",
    " " as "dispensationReference",
    getObsCodedValueInSectionByNames(p.patient_id, "Prophylaxis at INH", "Prophylaxis") as "INHGiven",
    " " as "sourceSitecode",
    getPatientMostRecentProgramOutcome(p.patient_id, 'en', 'HIV_PROGRAM_KEY') = "Dead" as "diedStatus",
    getObsCodedValue(p.patient_id, "cb654311-dac9-45e0-afc0-3c78ed432ea1") as "transferType",
    getPatientMostRecentProgramOutcome(p.patient_id, "en", "HIV_DEFAULTERS_PROGRAM_KEY") as "defaulterOutCome",
    getDurationMostRecentArvTreatmentInDays(p.patient_id, "#startDate#", "#endDate#") as "numberOfDays",
    getPatientMostRecentProgramAPSName(p.patient_id,'HIV_PROGRAM_KEY') as "caseManagerReference",
    " " as "nurseReference",
    getPatientMostRecentProgramAttributeValueFromName(p.patient_id, "PROGRAM_MANAGEMENT_4_PATIENT_DOCTOR_IN_CHARGE") as "doctorReference",
    " " as "previousRegimenId",
    " " as "regimenId",
    " " as "dispensationLocation",
    getPatientMostRecentProgramAttributeCodedValue(p.patient_id, '12afc1d3-74ba-428f-9a77-3fde76a136e4', "en") as "drugPickedUpBy",
    " " as "transferFromSiteCode",
    " " as "transferInReason",
    " " as "transferToSiteCode",
    " " as "transferOutReason",
    getNextAppointmentDate(p.patient_id) as "drugNextAppointmentDate",
    " " as "anchorRefline",
    getPatientMostRecentProgramTrackingStateValue(p.patient_id,"en","PMTCT_PROGRAM_KEY") as "isPregnantBool",
    " " as "breastFeedingOption",
    getObsNumericValue(p.patient_id, "5089AAAAAAAAAAAAAAAAAAAAAAAAAAAA") as "weight",
    " " as "CBOName",
    " " as "screenedForDisability",
    " " as "disabilityType",
    " " as "useAnAssitiveDevice",
    " " as "assistiveDevice",
    " " as "transferReasonCode",
    " " as "otherTransferReason",
    " " as "IITTreatmentSiteCode",
    getObsCodedValue(p.patient_id, "c4e7476f-2386-486a-ab4d-0fa8820d3110") as "taken3HP",
    " " as "BP",
    getObsNumericValue(p.patient_id, "5090AAAAAAAAAAAAAAAAAAAAAAAAAAAA") as "height",
    " " as "BMI",
    getObsNumericValue(p.patient_id, "c36e9c8b-3f10-11e4-adec-0800271c1b75") as "systolicBlood",
    getObsNumericValue(p.patient_id, "c379aa1d-3f10-11e4-adec-0800271c1b75") as "diastolicBlood",
    " " as "sideEffects",
    " " as "sideEffectsOthers",
    getPatientMostRecentProgramTrackingStateValue(p.patient_id,"en","HIV_PROGRAM_KEY") as "clinicalStage",
    getObsNumericValue(p.patient_id, "5e4b3b12-1e06-48fd-b665-d8204be100e4") as "CD4",
    " " as "CD4Date",
    " " as "advancedDisease",
    " " as "advancedDiseaseTreated",
    " " as "RHEZStartDate",
    " " as "RHEZStopDate",
    " " as "RHEZGiven",
    " " as "dispensationDate"
FROM patient p,(SELECT @a:= 0) AS a
WHERE
  patientHasEnrolledIntoHivProgramDuringReportingPeriod(p.patient_id, "#startDate#", "#endDate#");
