package org.jembi.bahmni.report_testing.test_utils.models;

public enum ReportEnum {
	PECG_REPORT("PECG_REPORT"),
	TESTING_REPORT("TESTING_REPORT"),
	TREATMENT_REPORT("TREATMENT_REPORT"),
	GEORGETOWN_INDEX_TESTING_REPORT("GEORGETOWN_INDEX_TESTING_REPORT"),
	GEORGETOWN_INH_FOLLOW_UP_REPORT("GEORGETOWN_INH_FOLLOW_UP_REPORT"),
	GEORGETOWN_TB_REPORT("GEORGETOWN_TB_REPORT"),
	GEORGETOWN_PATIENT_INFORMATION_REPORT("GEORGETOWN_PATIENT_INFORMATION_REPORT"),
	GEORGETOWN_VISIT_REPORT("GEORGETOWN_VISIT_REPORT"),
	GEORGETOWN_PCR_REPORT("GEORGETOWN_PCR_REPORT"),
	GEORGETOWN_TESTING_REPORT("GEORGETOWN_TESTING_REPORT"),
	GEORGETOWN_VIRAL_LOAD_REPORT("GEORGETOWN_VIRAL_LOAD_REPORT"),
	GEORGETOWN_ANC1_REPORT("GEORGETOWN_ANC1_REPORT"),
	GEORGETOWN_HIV_PATIENT_ON_TREATMENT_REPORT("GEORGETOWN_HIV_PATIENT_ON_TREATMENT_REPORT"),
	VIRAL_SUPPRESSION("VIRAL_SUPPRESSION"),
	CDV_TS_REPORT("HIV_TESTING_MONTHLY_INDICATOR_REPORT");

	private String value;

	ReportEnum(String value) {
		this.value = value;
	}

	public String toString() {
		return value;
	}
}
