SELECT 0 AS "HTS Client ID (EID or HEI Number) ",
	0 as "Date of birth (Date de naissance)",
	"" as "Current Age (Âge actuel)",
	"" as "Age (in months  for less than 5yrs) / Âge (en mois pour moins de 5 ans) ",
	"" as "Age Groups (Les groupes d'âge )",
	0 as "Sex",
	0 as "Pregnancy Status/état de grossesse ",
	0 as "KP Status/ Statut KP ",
	0 as "Actual date of visit for HTS(Date réelle de visite pour HTS)  OR EID Sample Collected date(Échantillon EID Date de collecte)  (dd-MMM-yyyy)",
	0 as "HTS Entry/ entrée (Testing Modality/ modalités de test)",
	0 as "HIV Status before ANC1/ Statut VIH avant l'CPN1 ",
	0 as "HTS Results/ Résultats HTS ",
	0 as "Location of testing/ emplacement des tests",
	0 as "Date Enrolled to HIV care (dd-MMM-yyyy)",
	"" as "Client ART Unique ID/Patient Unique ID/ART TARV",
	0 as "Linked to ART (Yes or No)",
	0 as "ART Start Date/ Date de début de l'ART  (dd-MMM-yyyy)",
	0 as "Name of Facility where Treatment is provided / Nom de l'établissement où le traitement est dispensé",
	0 as "Reasons for Non-Linkage / Raisons du non-couplage",
	"" as "Time to Enrolment (days)",
	"" as "Time to ART Initiation   (days)",
	0 as "Date offered ICT / Date offerte ICT",
	0 as "Date accepted ICT / Date d'acceptation ",
	0 as "No of contacts elicited/ Nombre de contacts obtenus",
	0 as "No of contacts notified / Nombre de contacts notifiés",
	0 as "No of contacts tested for HIV/ Nombre de contacts testés pour le VIH",
	0 as "No of contacts tested HIV positive/ Nombre de contacts testés séropositifs",
	0 as "APS";