SELECT "what to use here? Add 2 extra identifiers" AS "HTS Client ID (EID or HEI Number)",
	getPatientBirthdate(p.patient_id) as "Date of birth (Date de naissance)",
	"" as "Current Age (Âge actuel)",
	"" as "Age (in months  for less than 5yrs) / Âge (en mois pour moins de 5 ans) ",
	"" as "Age Groups (Les groupes d'âge )",
	getPatientGender(p.patient_id) as "Sex",
	getObsCodedValue(p.patient_id,"b2e1ffa5-a6a8-4f3d-b797-25f11a66293b") as "Pregnancy Status/état de grossesse ",
	getObsCodedValue(p.patient_id,"211f0857-61a3-4049-9777-374c4a592453") as "KP Status/ Statut KP ",
	0 as "Actual date of visit for HTS (Date réelle de visite pour HTS) OR EID Sample Collected date(Échantillon EID Date de collecte)  (dd-MMM-yyyy)",
	getObsCodedValue(p.patient_id,"bc43179d-00b4-4712-a5d6-4dabd4230888") as "HTS Entry/ entrée (Testing Modality/ modalités de test)",
	0 as "HIV Status before ANC1/ Statut VIH avant l'CPN1 ",
	0 as "HTS Results/ Résultats HTS",
	"what to use here? jessica recommends to add the location in the form" as "Location of testing/ emplacement des tests",
	getPatientDateOfEnrolmentInProgram(p.patient_id, "HIV_PROGRAM_KEY") as "Date Enrolled to HIV care (dd-MMM-yyyy)",
	getPatientARTNumber(p.patient_id) as "Client ART Unique ID/Patient Unique ID/ART TARV",
	IF(getPatientDateOfEnrolmentInProgram(p.patient_id, "HIV_PROGRAM_KEY"), "Yes", "No") as "Linked to ART (Yes or No)",
	getPatientARVStartDate(p.patient_id) as "ART Start Date/ Date de début de l'ART  (dd-MMM-yyyy)",
	getFacilityName() as "Name of Facility where Treatment is provided / Nom de l'établissement où le traitement est dispensé",
	"not in the system currently?" as "Reasons for Non-Linkage / Raisons du non-couplage",
	"days between hiv pos date and hiv enrollment" as "Time to Enrolment (days)",
	"days between hiv pos date and art start date" as "Time to ART Initiation (days)",
	getObsDatetimeValue(p.patient_id,"836fe9d4-96f1-4fea-9ad8-35bd06e0ee05") as "Date offered ICT / Date offerte ICT",
	getObsDatetimeValue(p.patient_id,"e7a002be-8afc-48b1-a81b-634e37f2961c") as "Date accepted ICT / Date d'acceptation ",
	IF(patientIsIndex(p.patient_id),getNumberOfContactsRelatedToIndex(p.patient_id),0) as "No of contacts elicited/ Nombre de contacts obtenus",
	IF(patientIsIndex(p.patient_id),getNumberOfEnrolledContactsRelatedToIndex(p.patient_id),0) as "No of contacts notified / Nombre de contacts notifiés",
	0 as "No of contacts tested for HIV/ Nombre de contacts testés pour le VIH",
	0 as "No of contacts tested HIV positive/ Nombre de contacts testés séropositifs",
	"HTC form" as "APS"
	FROM patient p;