SELECT getPatientDateOfEnrolmentInProgram(p.patient_id, "HIV_PROGRAM_KEY") AS "Enrollment Date/Date de l'inscription",
	getPatientARTNumber(p.patient_id) as "Patient Unique ID/ART №",
	getPatientGender(p.patient_id) as "Sex",
	getPatientBirthdate(p.patient_id) as "Date of birth / (Date de naissance)",
	"" as "Current Age (Âge actuel)",
	"" as "Age Groups (Les groupes d'âge )",
	getPatientARVStartDate(p.patient_id) as "ART Start Date/ Date de début de l'ART  (dd-MMM-yyyy)",
	"" as "Age at Start of ART (Years)",
	"" as "Age at Start of ART (Months) Enter for Under-5s ",
	0 as "Last ARV Pickup Date / Dernière date de prise en charge des ARV",
	"duration of ARV treatment in days" as "Days of ARV Refill / Jours de recharge ARV",
	0 as "Location of ARV refill / Emplacement de la recharge d'ARV",
	0 as "Differentiated ART delivery model at last ARV refil",
	0 as "Date eligible for Community ART dispensations (CAD)/ Date admissible aux dispensations de ART communautaire",
	0 as "Date newly enrolled in Community ART dispensations / Date à laquelle vous vous êtes nouvellement inscrit aux dispensations de ART communautaire",
	0 as "Next ART Pickup date/ Prochaine date de prise en charge ART",
	0 as "Regimen Line at ART Start/ Ligne de régime à ART Start",
	0 as "Regimen at ART Start/ Régime chez ART Start",
	0 as "Current Regimen Line/ Ligne de régime actuelle",
	0 as "Current ART Regimen/ Régime d'ART actuel",
	0 as "Regimen Switch/ Commutateur de régime",
	0 as "Date of Regimen switch  (limit only to the current reporting month)",
	patientIsPregnant(p.patient_id) as "Pregnancy Status/ Statut de grossesse",
	getObsCodedValue(p.patient_id,"211f0857-61a3-4049-9777-374c4a592453") as "KP Status",
	getViralLoadTestResult(p.patient_id) as "Current Viral Load / Charge virale actuelle (c/ml)",
	getViralLoadTestDate(p.patient_id) as "Date of Current Viral Load / Date de la charge virale actuelle (dd-mmm-yyyy)",
	0 as "Viral Load Indication/ Indication de la charge virale",
	0 as "Date of next Viral Load / Date de la prochaine charge virale (dd-mmm-yyyy)",
	0 as "Date of EAC 1  (dd-mmm-yyyy)",
	0 as "Date of EAC 2  (dd-mmm-yyyy)",
	"N/A" as "TB screening status at Last ARV Refill / Statut de dépistage de la tuberculose lors de la dernière recharge d'ARV",
	"N/A" as "Date initiated  TPT/ Date de lancement du TPT",
	"N/A" as "Date completed full course TPT/ Date de fin du cours complet TPT",
	0 as "Date of EAC 3 (dd/mm/yy)",
	getPatientMostRecentProgramOutcome(p.patient_id, "en", "HIV_PROGRAM_KEY") as "Current ART Status (Active, LTFU, Dead, Transferred Out, Stopped)",
	0 as "Status of Missed appointment / Statut de rendez-vous manqué",
	0 as "Psychosocial Agents (Retention APS)"
	FROM patient p;