SELECT 'Number of pregnant women registered for ANC 1 (first contact) in the month' AS 'Indicator1 Title', 
    PMTCT_Indicator1('#startDate#','#endDate#') AS 'Count1',
    'Number of pregnant who has done their first HIV test in the current pregnancy this month' AS 'Indicator2 Title', 
    PMTCT_Indicator2('#startDate#','#endDate#') AS 'Count2',
    'Number of pregnant women who withdrew the result of their HIV test during the month' AS 'Indicator3 Title', 
    PMTCT_Indicator3('#startDate#','#endDate#') AS 'Count3',
    'Number of pregnant women who has done their first HIV test and tested positive during the month' AS 'Indicator4 Title',
    PMTCT_Indicator4('#startDate#','#endDate#') AS 'Count4',
    'Number of pregnant women known to be HIV + on the moment of their first contact ANC' AS 'Indicator5 Title',
    PMTCT_Indicator5('#startDate#','#endDate#') AS 'Count5',
    'Not Available' AS 'Indicator6 Title', 0 AS 'Count6',
    'Not Available' AS 'Indicator7 Title', 0 AS 'Count7',
    'Not Available' AS 'Indicator8 Title', 0 AS 'Count8',
    'Not Available' AS 'Indicator9 Title', 0 AS 'Count9',
    'Not Available' AS 'Indicator10 Title', 0 AS 'Count10',
    'Not Available' AS 'Indicator11 Title', 0 AS 'Count11',
    'Not Available' AS 'Indicator12 Title', 0 AS 'Count12',
    'Not Available' AS 'Indicator13 Title', 0 AS 'Count13',
    'Not Available' AS 'Indicator14 Title', 0 AS 'Count14',
    'Not Available' AS 'Indicator15 Title', 0 AS 'Count15',
    'Not Available' AS 'Indicator16 Title', 0 AS 'Count16',
    'Not Available' AS 'Indicator17 Title', 0 AS 'Count17',
    'Not Available' AS 'Indicator18 Title', 0 AS 'Count18',
    'Not Available' AS 'Indicator19 Title', 0 AS 'Count19',
    'Not Available' AS 'Indicator20 Title', 0 AS 'Count20',
    'Not Available' AS 'Indicator21 Title', 0 AS 'Count21',
    'Not Available' AS 'Indicator22 Title', 0 AS 'Count22',
    'Not Available' AS 'Indicator23 Title', 0 AS 'Count23',
    'Not Available' AS 'Indicator24 Title', 0 AS 'Count24',
    'Not Available' AS 'Indicator25 Title', 0 AS 'Count25',
    'Not Available' AS 'Indicator26 Title', 0 AS 'Count26',
    'Not Available' AS 'Indicator27 Title', 0 AS 'Count27',
    'Not Available' AS 'Indicator28 Title', 0 AS 'Count28',
    'Not Available' AS 'Indicator29 Title', 0 AS 'Count29',
    'Not Available' AS 'Indicator30 Title', 0 AS 'Count30',
    'Not Available' AS 'Indicator31 Title', 0 AS 'Count31',
    'Not Available' AS 'Indicator32 Title', 0 AS 'Count32',
    'Not Available' AS 'Indicator33 Title', 0 AS 'Count33',
    'Not Available' AS 'Indicator34 Title', 0 AS 'Count34',
    'Not Available' AS 'Indicator35 Title', 0 AS 'Count35',
    'Not Available' AS 'Indicator36 Title', 0 AS 'Count36',
    'Not Available' AS 'Indicator37 Title', 0 AS 'Count37',
    'Not Available' AS 'Indicator38 Title', 0 AS 'Count38';
