SELECT
    " " as "reference",
    " " as "code",
    getPatientFullName(r.person_a) as "childName",
    getPatientBirthdate(r.person_a) as "birthDate",
    getPatientFullName(r.person_b) as "motherName",
    getPatientPhoneNumber(r.person_b) as "motherContact",
    " " as "referenceLab",
    getLabTestOrderDate(r.person_a, "PCR(ALERE-Q)", "#startDate#", "#endDate#") as "sampleDate1",
    getLabTestOrderDate(r.person_a, "PCR(ALERE-Q)", "#startDate#", "#endDate#") as "sendDate1",
    " " as "result1",
    " " as "resultDate1",
    " " as "sampleDate2",
    " " as "sendDate2",
    " " as "result2",
    " " as "resultDate2",
    " " as "sampleDate3",
    " " as "sendDate3",
    " " as "result3",
    " " as "resultDate3",
    " " as "sampleDate4",
    " " as "sendDate4",
    " " as "result4",
    " " as "resultDate4",
    getObsCodedValue(r.person_a, "9a4267a6-b9b7-11ed-afa1-0242ac120002") as "remark",
    " " as "siteCode",
    " " as "conso",
    getPatientGender(r.person_a) as "sex",
    IF(getProgramAttributeDateValueFromAttributeAndProgramName(r.person_a, "PROGRAM_MANAGEMENT_2_PATIENT_TREATMENT_DATE", "HIV_PROGRAM_KEY") IS NOT NULL, "Yes", "No") as "isChildOnArt",
    getProgramAttributeDateValueFromAttributeAndProgramName(r.person_a, "PROGRAM_MANAGEMENT_2_PATIENT_TREATMENT_DATE", "HIV_PROGRAM_KEY") as "dateOfInitiation",
    " " as "baselineReference",
    " " as "reasonsForNotInitiatingPatient",
    " " as "otherReasonsForNotInitiatingPatient",
    getObsCodedValue(r.person_a, "e44bd5a8-1c18-4e52-b86f-a16e48c07576") as "testResult1",
    getObsCodedValue(r.person_a, "2f72c035-b671-46f2-8487-f1b5a23e2480") as "testResult2",
    " " as "testResult3",
    getObsCodedValuesInNestedSectionByNames(r.person_a, "Kit Name", "First Test","HIV Test 1") as "serviceOrderReferenceKit1",
    getObsCodedValuesInNestedSectionByNames(r.person_a, "Kit Name", "Second Test","HIV Test 2") as "serviceOrderReferenceKit2",
    " " as "serviceOrderReferenceKit3",
    getObsDatetimeValue(r.person_a, "eedca3bb-d2b7-4ad5-a368-790457d574ab") as "RDTTestDate1",
    getObsCodedValue(r.person_a, "b0cccc64-d559-40f9-b0e7-3058172f3f56") as "RDTResult1",
    getObsCodedValue(r.person_a, "95b430d2-7c2b-4757-81c3-a028bebdc3d3") as "RDTResult2",
    getObsDatetimeValue(r.person_a, "88a50d28-826d-46a5-9aa9-085cf8d3a1cd") as "RDTTestDate2" 
FROM (SELECT @a:= 0) AS a, relationship r
    JOIN relationship_type rt ON rt.relationship_type_id = r.relationship AND rt.a_is_to_b = "RELATIONSHIP_BIO_MOTHER"
    JOIN patient_identifier pi ON pi.patient_id = r.person_a AND pi.preferred = 1
WHERE
    patientHasEnrolledIntoHivProgram(r.person_b) = "Yes";
  
