
-- update program names: This is done because the initializer sets the name as the concept name but we want to use a key instead
update program set name = 'HIV_PROGRAM_KEY' where name = 'HIV Program';
update program set name = 'TB_PROGRAM_KEY' where name = 'TB Program';
update program set name = 'HIV_DEFAULTERS_PROGRAM_KEY' where name = 'HIV Defaulters Program';
update program set name = 'INDEX_TESTING_PROGRAM_KEY' where name = 'Index Testing Program';
update program set name = 'VL_EAC_PROGRAM_KEY' where name = 'VL EAC Program';
update program set name = 'PMTCT_PROGRAM_KEY' where name = 'PMTCT Program';

update program set name = 'IPT_PROGRAM_KEY' where name = 'IPT Program';


-- update existing program attribute types
update program_attribute_type set description = 'PROGRAM_MANAGEMENT_ART_NUMBER', name = 'PROGRAM_MANAGEMENT_ART_NUMBER', datatype = 'org.openmrs.customdatatype.datatype.FreeTextDatatype', datatype_config = 'NULL' where name = 'ID_Number';
update program_attribute_type set description = 'PROGRAM_MANAGEMENT_PATIENT_STAGE', name = 'PROGRAM_MANAGEMENT_PATIENT_STAGE' where name = 'Stage';
update program_attribute_type set description = 'PROGRAM_MANAGEMENT_PATIENT_TREATMENT_DATE', name = 'PROGRAM_MANAGEMENT_PATIENT_TREATMENT_DATE' where name = 'Date';
update program_attribute_type set description = 'PROGRAM_MANAGEMENT_PATIENT_COMORBIDITES', name = 'PROGRAM_MANAGEMENT_PATIENT_COMORBIDITES', datatype = 'org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype', datatype_config = (select concept_id from concept where uuid = '6cf6c41e-9f39-4d92-a78d-18252eba93ff') where name = 'Co-morbidites';
update program_attribute_type set description = 'PROGRAM_MANAGEMENT_PATIENT_DOCTOR_IN_CHARGE', name = 'PROGRAM_MANAGEMENT_PATIENT_DOCTOR_IN_CHARGE' where name = 'Doctor';

-- add new program attribute types
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_LABEL_THERAPEUTIC_LINE","PROGRAM_MANAGEMENT_LABEL_THERAPEUTIC_LINE","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "397b7bc7-13ca-4e4e-abc3-bf854904dce3", (select concept_id from concept where uuid="397b7bc7-13ca-4e4e-abc3-bf854904dce3"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_8_LABEL_IS_BREASTFEEDING","PROGRAM_MANAGEMENT_8_LABEL_IS_BREASTFEEDING","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "242c9027-dc2d-42e6-869e-045e8a8b95cb");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_DURATION_ON_ART","PROGRAM_MANAGEMENT_DURATION_ON_ART","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "27441b69-84bd-4640-8682-92b6c0f449a0", (select concept_id from concept where uuid="8e259e94-b13d-48c4-a294-261aa243f92e"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_LAST_FAILED_APPOINTMENT_DATE","PROGRAM_MANAGEMENT_LAST_FAILED_APPOINTMENT_DATE","org.openmrs.customdatatype.datatype.DateDatatype", 1, NOW(), "88a312a2-51a6-47e4-b725-e5b8b545ac4c");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_PRETRACKING_OUTCOME","PROGRAM_MANAGEMENT_PRETRACKING_OUTCOME","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "0a51d8d0-c775-48a2-9ca2-42c269d00bc2", (select concept_id from concept where uuid="7239a3a0-da2a-4940-bfab-8418246988d7"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_RETURNED_TO_TREATMENT_DATE","PROGRAM_MANAGEMENT_RETURNED_TO_TREATMENT_DATE","org.openmrs.customdatatype.datatype.DateDatatype", 1, NOW(), "b04fb0b8-3a1c-46fa-bf83-922513016b6b");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_TRACKING_DATE","PROGRAM_MANAGEMENT_TRACKING_DATE","org.openmrs.customdatatype.datatype.DateDatatype", 1, NOW(), "9b4b2dd5-bc5e-44b9-ad95-333a7bbfee3c");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_APS_NAME","PROGRAM_MANAGEMENT_APS_NAME","org.openmrs.customdatatype.datatype.FreeTextDatatype", 1, NOW(), "8bb0bdc0-aaf3-4501-8954-d1b17226075b");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_TRACKING_OUTCOME","PROGRAM_MANAGEMENT_TRACKING_OUTCOME","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "caf6d807-861d-4393-9d6e-940b98fa712d", (select concept_id from concept where uuid="c76d63ec-b7e2-44a4-88e0-a9961b49b80a"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_701_STIGMA","PROGRAM_MANAGEMENT_701_STIGMA","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "b077caed-d8ac-47ee-8a19-91891e7468e8");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_702_LONG_DISTANCE","PROGRAM_MANAGEMENT_702_LONG_DISTANCE","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "d80606b7-a981-4b35-8e4a-229dab396ebb");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_703_COST_OF_TRANSPORT","PROGRAM_MANAGEMENT_703_COST_OF_TRANSPORT","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "e7fa2cd0-dfc1-4df9-a468-3fd1f997774c");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_704_SIDE_EFFECTS_OF_ARVS","PROGRAM_MANAGEMENT_704_SIDE_EFFECTS_OF_ARVS","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "94f13179-e372-4cdf-84e1-8c6eb24c2508");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_705_COST_OF_SERVICES","PROGRAM_MANAGEMENT_705_COST_OF_SERVICES","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "3ca7a7db-033d-4386-9916-e4b2ba42cd60");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_706_STAFF_ATTITUDE","PROGRAM_MANAGEMENT_706_STAFF_ATTITUDE","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "f6210a3e-dbbd-4e45-b76d-c2317903950a");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_707_TRADITIONAL_BELIEFS","PROGRAM_MANAGEMENT_707_TRADITIONAL_BELIEFS","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "42dd8fc3-1880-45e0-84b3-38777b213424");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_708_RELIGIOUS_BELIEFS","PROGRAM_MANAGEMENT_708_RELIGIOUS_BELIEFS","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "e865ec35-91c6-4cf3-9717-5d4c967af991");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_709_DENIAL","PROGRAM_MANAGEMENT_709_DENIAL","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "efcb1ed0-cd94-4310-8812-2d5071c76063");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_710_INCONVENIENT_SERVICE_HOURS","PROGRAM_MANAGEMENT_710_INCONVENIENT_SERVICE_HOURS","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "d2190415-2fb6-4b89-ae10-671409ebfe35");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_711_TRAVEL","PROGRAM_MANAGEMENT_711_TRAVEL","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "1f92db75-28bb-4574-a403-f5fe62f5a3ca");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_712_FEELS_HEALTHY","PROGRAM_MANAGEMENT_712_FEELS_HEALTHY","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "01e3bb51-ee07-44a9-abb5-dc5bdbaa33cf");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_713_INSECURITY","PROGRAM_MANAGEMENT_713_INSECURITY","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "e7ff8a41-951d-4142-a0b4-e110db2e79b8");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_714_OTHER_DEFAULTING_REASON","PROGRAM_MANAGEMENT_714_OTHER_DEFAULTING_REASON","org.openmrs.customdatatype.datatype.FreeTextDatatype", 1, NOW(), "37a86762-3eae-4c00-a004-6589407d0de1");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_OTHER_PROGRAM_OUTCOME","PROGRAM_MANAGEMENT_OTHER_PROGRAM_OUTCOME","org.openmrs.customdatatype.datatype.FreeTextDatatype", 1, NOW(), "404b652e-6002-4371-8427-3e9e84cdf454");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_1_NOTIFICATION_METHOD","PROGRAM_MANAGEMENT_1_NOTIFICATION_METHOD","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "47387502-5650-4b05-8570-99aa100e86b6", (select concept_id from concept where uuid="1cae0968-5235-11ea-8d77-2e728ce88125"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_2_NOTIFICATION_DATE","PROGRAM_MANAGEMENT_2_NOTIFICATION_DATE","org.openmrs.customdatatype.datatype.DateDatatype", 1, NOW(), "c4e1106e-1644-45be-86c2-88392e73a507");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_3_NOTIFICATION_OUTCOME","PROGRAM_MANAGEMENT_3_NOTIFICATION_OUTCOME","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "19a7ef7b-5748-477b-a973-2f170e687624", (select concept_id from concept where uuid="e8be7788-5233-11ea-8d77-2e728ce88125"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_4_CONTACT_TRACER","PROGRAM_MANAGEMENT_4_CONTACT_TRACER","org.openmrs.customdatatype.datatype.FreeTextDatatype", 1, NOW(), "d7246eea-5161-43e0-b840-d315c24cc95e");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_5_COMMENTS","PROGRAM_MANAGEMENT_5_COMMENTS","org.openmrs.customdatatype.datatype.FreeTextDatatype", 1, NOW(), "a404f7a7-1249-4b81-bb58-fd4e97e4798e");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_1_EAC_DATE","PROGRAM_MANAGEMENT_1_EAC_DATE","org.openmrs.customdatatype.datatype.DateDatatype", 1, NOW(), "13cfc4e2-49ba-470e-a2ac-81fa9bed607c");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_2_CLASSIFICATION_OF_ADHERENCE","PROGRAM_MANAGEMENT_2_CLASSIFICATION_OF_ADHERENCE","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "adf90c17-52bb-4ce3-8fb9-cde6e60e4a0d", (select concept_id from concept where uuid="b636bdf8-c054-4d6e-81ee-1cf6d04c798f"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_3_RESISTANCE_TEST_DONE","PROGRAM_MANAGEMENT_3_RESISTANCE_TEST_DONE","org.openmrs.customdatatype.datatype.BooleanDatatype", 1, NOW(), "4fae4c58-a5c7-4503-a972-a7ab5cb51443");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_90_DATE_ELIGIBLE_COMMUNITY_ART","PROGRAM_MANAGEMENT_90_DATE_ELIGIBLE_COMMUNITY_ART","org.openmrs.customdatatype.datatype.DateDatatype", 1, NOW(), "9948bf80-20f0-4c64-b5d8-fa3d12c5dd2d");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_91_DATE_ENROLLED_COMMUNITY_ART","PROGRAM_MANAGEMENT_91_DATE_ENROLLED_COMMUNITY_ART","org.openmrs.customdatatype.datatype.DateDatatype", 1, NOW(), "cd40c350-8912-42aa-9a11-abea2c110fb4");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_92_ART_DISPENSATION_MODEL","PROGRAM_MANAGEMENT_92_ART_DISPENSATION_MODEL","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "12afc1d3-74ba-428f-9a77-3fde76a136e4", (select concept_id from concept where uuid="ccd879e9-d9ff-4fab-b433-327e0f112387"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_93_DATE_STOPPED_COMMUNITY_ART","PROGRAM_MANAGEMENT_93_DATE_STOPPED_COMMUNITY_ART","org.openmrs.customdatatype.datatype.DateDatatype", 1, NOW(), "6cde453d-2c27-445a-8e63-b4758d7d95e7");

insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PMTCT_PROGRAM_MANAGEMENT_FP_METHOD","PMTCT_PROGRAM_MANAGEMENT_FP_METHOD","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "6d91fd1f-0198-4078-aafe-3367dd87afd3", (select concept_id from concept where uuid="58fa4284-a100-450e-91b6-e302032f6bf6"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PMTCT_PROGRAM_MANAGEMENT_ANC_CODE","PMTCT_PROGRAM_MANAGEMENT_ANC_CODE","org.openmrs.customdatatype.datatype.FreeTextDatatype", 1, NOW(), "d5d20829-9e46-4d50-a085-6cb98213a7ea");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PMTCT_PROGRAM_MANAGEMENT_APS_NAME","PMTCT_PROGRAM_MANAGEMENT_APS_NAME","org.openmrs.customdatatype.datatype.FreeTextDatatype", 1, NOW(), "2af46f9c-d572-4362-aa14-43d72eacb2aa");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_COUNTRY_TRANSFERRED_TO","PROGRAM_MANAGEMENT_COUNTRY_TRANSFERRED_TO","org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "ef91197d-4686-4429-b292-7d9b9fd3ba2b", (select concept_id from concept where uuid="d6a37f3d-ee40-4574-8831-5abf6ebbb654"));

INSERT INTO program_attribute_type (name, description, datatype, creator, date_created, uuid, datatype_config)
VALUES
    ("IPT_PROGRAM_MANAGEMENT_PROTOCOL", "IPT_PROGRAM_MANAGEMENT_PROTOCOL", "org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "be31afc6-7546-4be2-898d-0ab3340cb323", (SELECT concept_id FROM concept WHERE uuid="c4e7476f-2386-486a-ab4d-0fa8820d3110")),
    ("IPT_PROGRAM_MANAGEMENT_REASON_FOR_INITIATION", "IPT_PROGRAM_MANAGEMENT_REASON_FOR_INITIATION", "org.bahmni.module.bahmnicore.customdatatype.datatype.CodedConceptDatatype", 1, NOW(), "fd2695a4-366e-49ab-95d1-121112cba2f2", (SELECT concept_id FROM concept WHERE uuid="18181e9e-3fdb-4008-96fa-cd3ed7f5f4e2"))
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    description = VALUES(description),
    datatype = VALUES(datatype),
    creator = VALUES(creator),
    date_created = VALUES(date_created),
    datatype_config = VALUES(datatype_config);
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_FACILITY_TRANSFERED_TO","PROGRAM_MANAGEMENT_FACILITY_TRANSFERED_TO","org.openmrs.customdatatype.datatype.FreeTextDatatype", 1, NOW(), "8b2287d1-b5f0-4a1c-9334-134c1a511b3e");
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid, datatype_config) values("PROGRAM_MANAGEMENT_REASON_FOR_OUTCOME","PROGRAM_MANAGEMENT_REASON_FOR_OUTCOME","org.openmrs.customdatatype.datatype.FreeTextDatatype", 1, NOW(), "bda8a9a7-f81a-466d-949b-ec0b684301b7", (select concept_id from concept where uuid="b72d94c6-ab70-47ef-b8c9-0eb7d0c0100f"));
insert ignore into program_attribute_type(name, description, datatype,creator, date_created, uuid) values("PROGRAM_MANAGEMENT_OUTCOME_DATE","PROGRAM_MANAGEMENT_OUTCOME_DATE","org.openmrs.customdatatype.datatype.DateDatatype", 1, NOW(), "9c20e3b0-6bc1-45e8-a733-baa57340764c");

-- update some of the attribute type names so that they are displayed in order
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_1_DURATION_ON_ART', description = 'PROGRAM_MANAGEMENT_1_DURATION_ON_ART' where uuid = '27441b69-84bd-4640-8682-92b6c0f449a0';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_2_LAST_FAILED_APPOINTMENT_DATE', description = 'PROGRAM_MANAGEMENT_2_LAST_FAILED_APPOINTMENT_DATE' where uuid = '88a312a2-51a6-47e4-b725-e5b8b545ac4c';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_3_PRETRACKING_OUTCOME', description = 'PROGRAM_MANAGEMENT_3_PRETRACKING_OUTCOME' where uuid = '0a51d8d0-c775-48a2-9ca2-42c269d00bc2';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_4_TRACKING_DATE', description = 'PROGRAM_MANAGEMENT_4_TRACKING_DATE' where uuid = '9b4b2dd5-bc5e-44b9-ad95-333a7bbfee3c';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_5_APS_NAME', description = 'PROGRAM_MANAGEMENT_5_APS_NAME' where uuid = '8bb0bdc0-aaf3-4501-8954-d1b17226075b';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_6_TRACKING_OUTCOME', description = 'PROGRAM_MANAGEMENT_6_TRACKING_OUTCOME' where uuid = 'caf6d807-861d-4393-9d6e-940b98fa712d';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_9_RETURNED_TO_TREATMENT_DATE', description = 'PROGRAM_MANAGEMENT_9_RETURNED_TO_TREATMENT_DATE' where uuid = 'b04fb0b8-3a1c-46fa-bf83-922513016b6b';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_1_ART_NUMBER', description = 'PROGRAM_MANAGEMENT_1_ART_NUMBER' where uuid = 'c41f844e-a707-11e6-91e9-0800270d80ce';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_2_PATIENT_TREATMENT_DATE', description = 'PROGRAM_MANAGEMENT_2_PATIENT_TREATMENT_DATE' where uuid = '2dc1aafd-a708-11e6-91e9-0800270d80ce';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_3_PATIENT_COMORBIDITES', description = 'PROGRAM_MANAGEMENT_3_PATIENT_COMORBIDITES' where uuid = '62346a80-a708-11e6-91e9-0800270d80ce';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_4_PATIENT_DOCTOR_IN_CHARGE', description = 'PROGRAM_MANAGEMENT_4_PATIENT_DOCTOR_IN_CHARGE' where uuid = '1172915f-a709-11e6-91e9-0800270d80ce';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_5_PATIENT_STAGE', description = 'PROGRAM_MANAGEMENT_5_PATIENT_STAGE' where uuid = '39202f47-a709-11e6-91e9-0800270d80ce';
update program_attribute_type set name = 'PROGRAM_MANAGEMENT_6_LABEL_THERAPEUTIC_LINE', description = 'PROGRAM_MANAGEMENT_6_LABEL_THERAPEUTIC_LINE' where uuid = '397b7bc7-13ca-4e4e-abc3-bf854904dce3';
